#ifndef JASS_h__
#define JASS_h__

#include <vector>

#ifdef _DEFINE_VARS
// declared in JASS.cpp
#define JASSFN(name, type, params)  typedef type name##_t params; name##_t* j##name = (name##_t*)GetJASSPtr(#name)
#else
#define JASSFN(name, type, params)  typedef type name##_t params; extern name##_t* j##name
#endif

struct CStringRep{ // the actual class name is CStringRep ;)
  DWORD vtable;    //0x00
  DWORD refCount;  // 0x04 ?
  DWORD dwUnk1;    // 0x08 ?
  DWORD pUnk2;     // 0x0C ?
  DWORD pUnk3;     // 0x10 ?
  DWORD pUnk4;     // 0x14 this-0xC .o0
  DWORD pUnk5;     // 0x18
  char* data;      // 0x1C ...

  /* sample data :
  0000 - pointer to   ->6F954658      ->6F954658
  0004 - Dword                 2               1
  0008 - Dword         790393882      3076342506
  000C - pointer to   ->1942F14C      ->1942230C
  0010 - pointer to   ->078191FC      ->13FE454C
  0014 - pointer to   ->13FF3C60      ->13FF3C80
  0018 - pointer to   ->13FF3C8C      ->13FF3CAC
  001C - pointer to   ->1262B848      ->1262B858
  */
};

struct RCString{
  DWORD vtable;     //0x00
  DWORD dw0;        //0x04  - always 0 ?
  CStringRep* data; //0x08
  DWORD dw1;        //0x0C  - string type ? probably... there is also RCStaticString etc...

  /* sample data :
  0000 - pointer to   ->6F87688C      ->6F87688C
  0004 - Dword    0           0
  0008 - pointer to   ->13FF3C6C      ->13FF3C6C
  000C - Word     15          15
  */
};

struct JASSVar
{
  long hash;                 // 0x0
  struct HT_Bucket* parent;  // 0x4
  struct JASSVar* next;      // 0x8
  char unk[0x8];             // 0xC
  long name;                 // 0x14
  long vartype;              // 0x18
  long vartype2;             // 0x1C
  long value;                // 0x20
  long is_func_arg;          // 0x24
};

struct JASSArray {
  long x0;
  long size;
  long length;
  long *data;
};

typedef struct {
  char unk[0x18];
  // off by 4!
  const char *name;         //0x18
  int address;              //0x1C
  int narg;                 //0x20
  const char *prototype;    //0x24
  int a;                    //0x28
  int b;                    //0x2C
  int c;                    //0x30
  int d;                    //0x34
  int rettype;              //0x38
} native_info;

DWORD GetJassVM(void);
string jStrGet(HANDLE h);
unsigned long getNumStrings(void);
RCString* MapString(const char* s);

void* GetJASSPtr(const char*);
JASSVar* GetJassVar(const char*);

union DWFP
{
  DWORD dw;
  float fl;
};

JASSFN(AbilityId, int __cdecl, (RCString*));
JASSFN(AbilityId2String, HANDLE /*String*/ __cdecl, ());
JASSFN(Acos, DWFP __cdecl, (float*));
JASSFN(AddHeroXP, void __cdecl, (HANDLE /* Unit */, int, bool));
JASSFN(AddIndicator, void __cdecl, (HANDLE /* Widget */, int, int, int, int));
JASSFN(AddItemToAllStock, void __cdecl, (int, int, int));
JASSFN(AddItemToStock, void __cdecl, (HANDLE /* Unit */, int, int, int));
JASSFN(AddLightning, HANDLE /* Lightning */ __cdecl, (RCString*, bool, float*, float*, float*, float*));
JASSFN(AddLightningEx, HANDLE /* Lightning */ __cdecl, (RCString*, bool, float*, float*, float*, float*, float*, float*));
JASSFN(AddPlayerTechResearched, void __cdecl, (HANDLE /* Player */, int, int));
JASSFN(AddResourceAmount, void __cdecl, (HANDLE /* Unit */, int));
JASSFN(AddSpecialEffect, HANDLE /* Effect */ __cdecl, (RCString*, float*, float*));
JASSFN(AddSpecialEffectLoc, HANDLE /* Effect */ __cdecl, (RCString*, HANDLE /* Location */));
JASSFN(AddSpecialEffectTarget, HANDLE /* Effect */ __cdecl, (RCString*, HANDLE /* Widget */, RCString*));
JASSFN(AddSpellEffect, HANDLE /* Effect */ __cdecl, (RCString*, HANDLE /* Effecttype */, float*, float*));
JASSFN(AddSpellEffectById, HANDLE /* Effect */ __cdecl, (int, HANDLE /* Effecttype */, float*, float*));
JASSFN(AddSpellEffectByIdLoc, HANDLE /* Effect */ __cdecl, (int, HANDLE /* Effecttype */, HANDLE /* Location */));
JASSFN(AddSpellEffectLoc, HANDLE /* Effect */ __cdecl, (RCString*, HANDLE /* Effecttype */, HANDLE /* Location */));
JASSFN(AddSpellEffectTarget, HANDLE /* Effect */ __cdecl, (RCString*, HANDLE /* Effecttype */, HANDLE /* Widget */, RCString*));
JASSFN(AddSpellEffectTargetById, HANDLE /* Effect */ __cdecl, (int, HANDLE /* Effecttype */, HANDLE /* Widget */, RCString*));
JASSFN(AddUnitAnimationProperties, void __cdecl, (HANDLE /* Unit */, RCString*, bool));
JASSFN(AddUnitToAllStock, void __cdecl, (int, int, int));
JASSFN(AddUnitToStock, void __cdecl, (HANDLE /* Unit */, int, int, int));
JASSFN(AddWeatherEffect, HANDLE /* Weathereffect */ __cdecl, (HANDLE /* Rect */, int));
JASSFN(AdjustCameraField, void __cdecl, (HANDLE /* Camerafield */, float*, float*));
JASSFN(And, HANDLE /* Boolexpr */ __cdecl, (HANDLE /* Boolexpr */, HANDLE /* Boolexpr */));
JASSFN(Asin, DWFP __cdecl, (float*));
JASSFN(Atan, DWFP __cdecl, (float*));
JASSFN(Atan2, DWFP __cdecl, (float*, float*));
JASSFN(AttachSoundToUnit, void __cdecl, (HANDLE /* Sound */, HANDLE /* Unit */));
JASSFN(CachePlayerHeroData, void __cdecl, (HANDLE /* Player */));
JASSFN(CameraSetSmoothingFactor, void __cdecl, (float*));
JASSFN(CameraSetSourceNoise, void __cdecl, (float*, float*));
JASSFN(CameraSetSourceNoiseEx, void __cdecl, (float*, float*, bool));
JASSFN(CameraSetTargetNoise, void __cdecl, (float*, float*));
JASSFN(CameraSetTargetNoiseEx, void __cdecl, (float*, float*, bool));
JASSFN(CameraSetupApply, void __cdecl, (HANDLE /* Camerasetup */, bool, bool));
JASSFN(CameraSetupApplyForceDuration, void __cdecl, (HANDLE /* Camerasetup */, bool, float*));
JASSFN(CameraSetupApplyForceDurationWithZ, void __cdecl, (HANDLE /* Camerasetup */, float*, float*));
JASSFN(CameraSetupApplyWithZ, void __cdecl, (HANDLE /* Camerasetup */, float*));
JASSFN(CameraSetupGetDestPositionLoc, HANDLE /* Location */ __cdecl, (HANDLE /* Camerasetup */));
JASSFN(CameraSetupGetDestPositionX, DWFP __cdecl, (HANDLE /* Camerasetup */));
JASSFN(CameraSetupGetDestPositionY, DWFP __cdecl, (HANDLE /* Camerasetup */));
JASSFN(CameraSetupGetField, DWFP __cdecl, (HANDLE /* Camerasetup */, HANDLE /* Camerafield */));
JASSFN(CameraSetupSetDestPosition, void __cdecl, (HANDLE /* Camerasetup */, float*, float*, float*));
JASSFN(CameraSetupSetField, void __cdecl, (HANDLE /* Camerasetup */, HANDLE /* Camerafield */, float*, float*));
JASSFN(ChangeLevel, void __cdecl, (RCString*, bool));
JASSFN(Cheat, void __cdecl, (RCString*));
JASSFN(ChooseRandomCreep, int __cdecl, ());
JASSFN(ChooseRandomItem, int __cdecl, ());
JASSFN(ChooseRandomItemEx, int __cdecl, (HANDLE /* Itemtype */, int));
JASSFN(ChooseRandomNPBuilding, int __cdecl, ());
JASSFN(ClearMapMusic, void __cdecl, ());
JASSFN(ClearSelection, void __cdecl, ());
JASSFN(ClearStackedSound, void __cdecl, (RCString*, float*, float*));
JASSFN(ClearStackedSoundRect, void __cdecl, (RCString*, HANDLE /* Rect */));
JASSFN(ClearTextMessages, void __cdecl, ());
JASSFN(CommandAI, void __cdecl, (HANDLE /* Player */, int, int));
JASSFN(Condition, HANDLE /* Conditionfunc */ __cdecl, ());
JASSFN(ConvertAIDifficulty, HANDLE /* Aidifficulty */ __cdecl, ());
JASSFN(ConvertAllianceType, HANDLE /* Alliancetype */ __cdecl, ());
JASSFN(ConvertAttackType, HANDLE /* Attacktype */ __cdecl, ());
JASSFN(ConvertBlendMode, HANDLE /* Blendmode */ __cdecl, ());
JASSFN(ConvertCameraField, HANDLE /* Camerafield */ __cdecl, ());
JASSFN(ConvertDamageType, HANDLE /* Damagetype */ __cdecl, ());
JASSFN(ConvertDialogEvent, HANDLE /* Dialogevent */ __cdecl, ());
JASSFN(ConvertEffectType, HANDLE /* Effecttype */ __cdecl, ());
JASSFN(ConvertFGameState, HANDLE /* Fgamestate */ __cdecl, ());
JASSFN(ConvertFogState, HANDLE /* Fogstate */ __cdecl, ());
JASSFN(ConvertGameDifficulty, HANDLE /* Gamedifficulty */ __cdecl, ());
JASSFN(ConvertGameEvent, HANDLE /* Gameevent */ __cdecl, ());
JASSFN(ConvertGameSpeed, HANDLE /* Gamespeed */ __cdecl, ());
JASSFN(ConvertGameType, HANDLE /* Gametype */ __cdecl, ());
JASSFN(ConvertIGameState, HANDLE /* Igamestate */ __cdecl, ());
JASSFN(ConvertItemType, HANDLE /* Itemtype */ __cdecl, ());
JASSFN(ConvertLimitOp, HANDLE /* Limitop */ __cdecl, ());
JASSFN(ConvertMapControl, HANDLE /* Mapcontrol */ __cdecl, ());
JASSFN(ConvertMapDensity, HANDLE /* Mapdensity */ __cdecl, ());
JASSFN(ConvertMapFlag, HANDLE /* Mapflag */ __cdecl, ());
JASSFN(ConvertMapSetting, HANDLE /* Mapsetting */ __cdecl, ());
JASSFN(ConvertMapVisibility, HANDLE /* Mapvisibility */ __cdecl, ());
JASSFN(ConvertPathingType, HANDLE /* Pathingtype */ __cdecl, ());
JASSFN(ConvertPlacement, HANDLE /* Placement */ __cdecl, ());
JASSFN(ConvertPlayerColor, HANDLE /* Playercolor */ __cdecl, ());
JASSFN(ConvertPlayerEvent, HANDLE /* Playerevent */ __cdecl, ());
JASSFN(ConvertPlayerGameResult, HANDLE /* Playergameresult */ __cdecl, ());
JASSFN(ConvertPlayerScore, HANDLE /* Playerscore */ __cdecl, ());
JASSFN(ConvertPlayerSlotState, HANDLE /* Playerslotstate */ __cdecl, ());
JASSFN(ConvertPlayerState, HANDLE /* Playerstate */ __cdecl, ());
JASSFN(ConvertPlayerUnitEvent, HANDLE /* Playerunitevent */ __cdecl, ());
JASSFN(ConvertRace, HANDLE /* Race */ __cdecl, ());
JASSFN(ConvertRacePref, HANDLE /* Racepreference */ __cdecl, ());
JASSFN(ConvertRarityControl, HANDLE /* Raritycontrol */ __cdecl, ());
JASSFN(ConvertSoundType, HANDLE /* Soundtype */ __cdecl, ());
JASSFN(ConvertStartLocPrio, HANDLE /* Startlocprio */ __cdecl, ());
JASSFN(ConvertTexMapFlags, HANDLE /* Texmapflags */ __cdecl, ());
JASSFN(ConvertUnitEvent, HANDLE /* Unitevent */ __cdecl, ());
JASSFN(ConvertUnitState, HANDLE /* Unitstate */ __cdecl, ());
JASSFN(ConvertUnitType, HANDLE /* Unittype */ __cdecl, ());
JASSFN(ConvertVersion, HANDLE /* Version */ __cdecl, ());
JASSFN(ConvertVolumeGroup, HANDLE /* Volumegroup */ __cdecl, ());
JASSFN(ConvertWeaponType, HANDLE /* Weapontype */ __cdecl, ());
JASSFN(ConvertWidgetEvent, HANDLE /* Widgetevent */ __cdecl, ());
JASSFN(CopySaveGame, bool __cdecl, (RCString*, RCString*));
JASSFN(Cos, DWFP __cdecl, (float*));
JASSFN(CreateBlightedGoldmine, HANDLE /* Unit */ __cdecl, (HANDLE /* Player */, float*, float*, float*));
JASSFN(CreateCameraSetup, HANDLE /* Camerasetup */ __cdecl, ());
JASSFN(CreateCorpse, HANDLE /* Unit */ __cdecl, (HANDLE /* Player */, int, float*, float*, float*));
JASSFN(CreateDeadDestructable, HANDLE /* Destructable */ __cdecl, (int, float*, float*, float*, float*, int));
JASSFN(CreateDeadDestructableZ, HANDLE /* Destructable */ __cdecl, (int, float*, float*, float*, float*, float*, int));
JASSFN(CreateDefeatCondition, HANDLE /* Defeatcondition */ __cdecl, ());
JASSFN(CreateDestructable, HANDLE /* Destructable */ __cdecl, (int, float*, float*, float*, float*, int));
JASSFN(CreateDestructableZ, HANDLE /* Destructable */ __cdecl, (int, float*, float*, float*, float*, float*, int));
JASSFN(CreateFogModifierRadius, HANDLE /* Fogmodifier */ __cdecl, (HANDLE /* Player */, HANDLE /* Fogstate */, float*, float*, float*, bool, bool));
JASSFN(CreateFogModifierRadiusLoc, HANDLE /* Fogmodifier */ __cdecl, (HANDLE /* Player */, HANDLE /* Fogstate */, HANDLE /* Location */, float*, bool, bool));
JASSFN(CreateFogModifierRect, HANDLE /* Fogmodifier */ __cdecl, (HANDLE /* Player */, HANDLE /* Fogstate */, HANDLE /* Rect */, bool, bool));
JASSFN(CreateForce, HANDLE /* Force */ __cdecl, ());
JASSFN(CreateGroup, HANDLE /* Group */ __cdecl, ());
JASSFN(CreateImage, HANDLE /* Image */ __cdecl, (RCString*, float*, float*, float*, float*, float*, float*, float*, float*, float*, int));
JASSFN(CreateItem, HANDLE /* Item */ __cdecl, (int, float*, float*));
JASSFN(CreateItemPool, HANDLE /* Itempool */ __cdecl, ());
JASSFN(CreateLeaderboard, HANDLE /* Leaderboard */ __cdecl, ());
JASSFN(CreateMIDISound, HANDLE /* Sound */ __cdecl, (RCString*, int, int));
JASSFN(CreateMultiboard, HANDLE /* Multiboard */ __cdecl, ());
JASSFN(CreateQuest, HANDLE /* Quest */ __cdecl, ());
JASSFN(CreateRegion, HANDLE /* Region */ __cdecl, ());
JASSFN(CreateSound, HANDLE /* Sound */ __cdecl, (RCString*, bool, bool, bool, int, int, RCString*));
JASSFN(CreateSoundFilenameWithLabel, HANDLE /* Sound */ __cdecl, (RCString*, bool, bool, bool, int, int, RCString*));
JASSFN(CreateSoundFromLabel, HANDLE /* Sound */ __cdecl, (RCString*, bool, bool, bool, int, int));
JASSFN(CreateTextTag, HANDLE /* Texttag */ __cdecl, ());
JASSFN(CreateTimer, HANDLE /* Timer */ __cdecl, ());
JASSFN(CreateTimerDialog, HANDLE /* Timerdialog */ __cdecl, (HANDLE /* Timer */));
JASSFN(CreateTrackable, HANDLE /* Trackable */ __cdecl, (RCString*, float*, float*, float*));
JASSFN(CreateTrigger, HANDLE /* Trigger */ __cdecl, ());
JASSFN(CreateUbersplat, HANDLE /* Ubersplat */ __cdecl, (float*, float*, RCString*, int, int, int, int, bool, bool));
JASSFN(CreateUnit, HANDLE /* Unit */ __cdecl, (HANDLE /* Player */, int, float*, float*, float*));
JASSFN(CreateUnitAtLoc, HANDLE /* Unit */ __cdecl, (HANDLE /* Player */, int, HANDLE /* Location */, float*));
JASSFN(CreateUnitAtLocByName, HANDLE /* Unit */ __cdecl, (HANDLE /* Player */, RCString*, HANDLE /* Location */, float*));
JASSFN(CreateUnitByName, HANDLE /* Unit */ __cdecl, (HANDLE /* Player */, RCString*, float*, float*, float*));
JASSFN(CreateUnitPool, HANDLE /* Unitpool */ __cdecl, ());
JASSFN(CripplePlayer, void __cdecl, (HANDLE /* Player */, HANDLE /* Force */, bool));
JASSFN(DecUnitAbilityLevel, int __cdecl, (HANDLE /* Unit */, int));
JASSFN(DefeatConditionSetDescription, void __cdecl, (HANDLE /* Defeatcondition */, RCString*));
JASSFN(DefineStartLocation, void __cdecl, (int, float*, float*));
JASSFN(DefineStartLocationLoc, void __cdecl, (int, HANDLE /* Location */));
JASSFN(Deg2Rad, DWFP __cdecl, (float*));
JASSFN(DestroyBoolExpr, void __cdecl, (HANDLE /* Boolexpr */));
JASSFN(DestroyCondition, void __cdecl, (HANDLE /* Conditionfunc */));
JASSFN(DestroyDefeatCondition, void __cdecl, (HANDLE /* Defeatcondition */));
JASSFN(DestroyEffect, void __cdecl, (HANDLE /* Effect */));
JASSFN(DestroyFilter, void __cdecl, (HANDLE /* Filterfunc */));
JASSFN(DestroyFogModifier, void __cdecl, (HANDLE /* Fogmodifier */));
JASSFN(DestroyForce, void __cdecl, (HANDLE /* Force */));
JASSFN(DestroyGroup, void __cdecl, (HANDLE /* Group */));
JASSFN(DestroyImage, void __cdecl, (HANDLE /* Image */));
JASSFN(DestroyItemPool, void __cdecl, (HANDLE /* Itempool */));
JASSFN(DestroyLeaderboard, void __cdecl, (HANDLE /* Leaderboard */));
JASSFN(DestroyLightning, bool __cdecl, (HANDLE /* Lightning */));
JASSFN(DestroyMultiboard, void __cdecl, (HANDLE /* Multiboard */));
JASSFN(DestroyQuest, void __cdecl, (HANDLE /* Quest */));
JASSFN(DestroyTextTag, void __cdecl, (HANDLE /* Texttag */));
JASSFN(DestroyTimer, void __cdecl, (HANDLE /* Timer */));
JASSFN(DestroyTimerDialog, void __cdecl, (HANDLE /* Timerdialog */));
JASSFN(DestroyTrigger, void __cdecl, (HANDLE /* Trigger */));
JASSFN(DestroyUbersplat, void __cdecl, (HANDLE /* Ubersplat */));
JASSFN(DestroyUnitPool, void __cdecl, (HANDLE /* Unitpool */));
JASSFN(DestructableRestoreLife, void __cdecl, (HANDLE /* Destructable */, float*, bool));
JASSFN(DialogAddButton, HANDLE /* Button */ __cdecl, (HANDLE /* Dialog */, RCString*, int));
JASSFN(DialogAddQuitButton, HANDLE /* Button */ __cdecl, (HANDLE /* Dialog */, bool, RCString*, int));
JASSFN(DialogClear, void __cdecl, (HANDLE /* Dialog */));
JASSFN(DialogCreate, HANDLE /* Dialog */ __cdecl, ());
JASSFN(DialogDestroy, void __cdecl, (HANDLE /* Dialog */));
JASSFN(DialogDisplay, void __cdecl, (HANDLE /* Player */, HANDLE /* Dialog */, bool));
JASSFN(DialogSetAsync, void __cdecl, (HANDLE /* Dialog */));
JASSFN(DialogSetMessage, void __cdecl, (HANDLE /* Dialog */, RCString*));
JASSFN(DisableRestartMission, void __cdecl, ());
JASSFN(DisableTrigger, void __cdecl, (HANDLE /* Trigger */));
JASSFN(DisplayCineFilter, void __cdecl, ());
JASSFN(DisplayLoadDialog, void __cdecl, ());
JASSFN(DisplayTextToPlayer, void __cdecl, (HANDLE /* Player */, float*, float*, RCString*));
JASSFN(DisplayTimedTextFromPlayer, void __cdecl, (HANDLE /* Player */, float*, float*, float*, RCString*));
JASSFN(DisplayTimedTextToPlayer, void __cdecl, (HANDLE /* Player */, float*, float*, float*, RCString*));
JASSFN(DoNotSaveReplay, void __cdecl, ());
JASSFN(EnableDragSelect, void __cdecl, (bool, bool));
JASSFN(EnableMinimapFilterButtons, void __cdecl, (bool, bool));
JASSFN(EnableOcclusion, void __cdecl, ());
JASSFN(EnablePreSelect, void __cdecl, (bool, bool));
JASSFN(EnableSelect, void __cdecl, (bool, bool));
JASSFN(EnableTrigger, void __cdecl, (HANDLE /* Trigger */));
JASSFN(EnableUserControl, void __cdecl, ());
JASSFN(EnableUserUI, void __cdecl, ());
JASSFN(EnableWeatherEffect, void __cdecl, (HANDLE /* Weathereffect */, bool));
JASSFN(EnableWorldFogBoundary, void __cdecl, ());
JASSFN(EndCinematicScene, void __cdecl, ());
JASSFN(EndGame, void __cdecl, ());
JASSFN(EndThematicMusic, void __cdecl, ());
JASSFN(EnumDestructablesInRect, void __cdecl, (HANDLE /* Rect */, HANDLE /* Boolexpr */, DWORD));
JASSFN(EnumItemsInRect, void __cdecl, (HANDLE /* Rect */, HANDLE /* Boolexpr */, DWORD));
JASSFN(ExecuteFunc, void __cdecl, (RCString*));
JASSFN(Filter, HANDLE /* Filterfunc */ __cdecl, ());
JASSFN(FinishUbersplat, void __cdecl, (HANDLE /* Ubersplat */));
JASSFN(FirstOfGroup, HANDLE /* Unit */ __cdecl, (HANDLE /* Group */));
JASSFN(FlashQuestDialogButton, void __cdecl, ());
JASSFN(FlushChildHashtable, void __cdecl, (HANDLE /* Hashtable */, int));
JASSFN(FlushGameCache, void __cdecl, (HANDLE /* Gamecache */));
JASSFN(FlushParentHashtable, void __cdecl, (HANDLE /* Hashtable */));
JASSFN(FlushStoredBoolean, void __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*));
JASSFN(FlushStoredInteger, void __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*));
JASSFN(FlushStoredMission, void __cdecl, (HANDLE /* Gamecache */, RCString*));
JASSFN(FlushStoredReal, void __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*));
JASSFN(FlushStoredString, void __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*));
JASSFN(FlushStoredUnit, void __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*));
JASSFN(FogEnable, void __cdecl, ());
JASSFN(FogMaskEnable, void __cdecl, ());
JASSFN(FogModifierStart, void __cdecl, (HANDLE /* Fogmodifier */));
JASSFN(FogModifierStop, void __cdecl, (HANDLE /* Fogmodifier */));
JASSFN(ForForce, void __cdecl, (HANDLE /* Force */, DWORD));
JASSFN(ForGroup, void __cdecl, (HANDLE /* Group */, DWORD));
JASSFN(ForceAddPlayer, void __cdecl, (HANDLE /* Force */, HANDLE /* Player */));
JASSFN(ForceCampaignSelectScreen, void __cdecl, ());
JASSFN(ForceCinematicSubtitles, void __cdecl, ());
JASSFN(ForceClear, void __cdecl, (HANDLE /* Force */));
JASSFN(ForceEnumAllies, void __cdecl, (HANDLE /* Force */, HANDLE /* Player */, HANDLE /* Boolexpr */));
JASSFN(ForceEnumEnemies, void __cdecl, (HANDLE /* Force */, HANDLE /* Player */, HANDLE /* Boolexpr */));
JASSFN(ForceEnumPlayers, void __cdecl, (HANDLE /* Force */, HANDLE /* Boolexpr */));
JASSFN(ForceEnumPlayersCounted, void __cdecl, (HANDLE /* Force */, HANDLE /* Boolexpr */, int));
JASSFN(ForcePlayerStartLocation, void __cdecl, (HANDLE /* Player */, int));
JASSFN(ForceQuestDialogUpdate, void __cdecl, ());
JASSFN(ForceRemovePlayer, void __cdecl, (HANDLE /* Force */, HANDLE /* Player */));
JASSFN(ForceUICancel, void __cdecl, ());
JASSFN(ForceUIKey, void __cdecl, (RCString*));
JASSFN(GetAIDifficulty, HANDLE /* Aidifficulty */ __cdecl, (HANDLE /* Player */));
JASSFN(GetAbilityEffect, HANDLE /*String*/ __cdecl, (RCString*, HANDLE /* Effecttype */, int));
JASSFN(GetAbilityEffectById, HANDLE /*String*/ __cdecl, (int, HANDLE /* Effecttype */, int));
JASSFN(GetAbilitySound, HANDLE /*String*/ __cdecl, (RCString*, HANDLE /* Soundtype */));
JASSFN(GetAbilitySoundById, HANDLE /*String*/ __cdecl, (int, HANDLE /* Soundtype */));
JASSFN(GetAllyColorFilterState, int __cdecl, ());
JASSFN(GetAttacker, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetBuyingUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetCameraBoundMaxX, DWFP __cdecl, ());
JASSFN(GetCameraBoundMaxY, DWFP __cdecl, ());
JASSFN(GetCameraBoundMinX, DWFP __cdecl, ());
JASSFN(GetCameraBoundMinY, DWFP __cdecl, ());
JASSFN(GetCameraEyePositionLoc, HANDLE /* Location */ __cdecl, ());
JASSFN(GetCameraEyePositionX, DWFP __cdecl, ());
JASSFN(GetCameraEyePositionY, DWFP __cdecl, ());
JASSFN(GetCameraEyePositionZ, DWFP __cdecl, ());
JASSFN(GetCameraField, DWFP __cdecl, (HANDLE /* Camerafield */));
JASSFN(GetCameraMargin, DWFP __cdecl, ());
JASSFN(GetCameraTargetPositionLoc, HANDLE /* Location */ __cdecl, ());
JASSFN(GetCameraTargetPositionX, DWFP __cdecl, ());
JASSFN(GetCameraTargetPositionY, DWFP __cdecl, ());
JASSFN(GetCameraTargetPositionZ, DWFP __cdecl, ());
JASSFN(GetCancelledStructure, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetChangingUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetChangingUnitPrevOwner, HANDLE /* Player */ __cdecl, ());
JASSFN(GetClickedButton, HANDLE /* Button */ __cdecl, ());
JASSFN(GetClickedDialog, HANDLE /* Dialog */ __cdecl, ());
JASSFN(GetConstructedStructure, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetConstructingStructure, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetCreatureDensity, HANDLE /* Mapdensity */ __cdecl, ());
JASSFN(GetCreepCampFilterState, bool __cdecl, ());
JASSFN(GetCustomCampaignButtonVisible, bool __cdecl, ());
JASSFN(GetDecayingUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetDefaultDifficulty, HANDLE /* Gamedifficulty */ __cdecl, ());
JASSFN(GetDestructableLife, DWFP __cdecl, (HANDLE /* Destructable */));
JASSFN(GetDestructableMaxLife, DWFP __cdecl, (HANDLE /* Destructable */));
JASSFN(GetDestructableName, HANDLE /*String*/ __cdecl, (HANDLE /* Destructable */));
JASSFN(GetDestructableOccluderHeight, DWFP __cdecl, (HANDLE /* Destructable */));
JASSFN(GetDestructableTypeId, int __cdecl, (HANDLE /* Destructable */));
JASSFN(GetDestructableX, DWFP __cdecl, (HANDLE /* Destructable */));
JASSFN(GetDestructableY, DWFP __cdecl, (HANDLE /* Destructable */));
JASSFN(GetDetectedUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetDyingUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetEnteringUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetEnumDestructable, HANDLE /* Destructable */ __cdecl, ());
JASSFN(GetEnumItem, HANDLE /* Item */ __cdecl, ());
JASSFN(GetEnumPlayer, HANDLE /* Player */ __cdecl, ());
JASSFN(GetEnumUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetEventDamage, DWFP __cdecl, ());
JASSFN(GetEventDamageSource, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetEventDetectingPlayer, HANDLE /* Player */ __cdecl, ());
JASSFN(GetEventGameState, HANDLE /* Gamestate */ __cdecl, ());
JASSFN(GetEventPlayerChatString, HANDLE /*String*/ __cdecl, ());
JASSFN(GetEventPlayerChatStringMatched, HANDLE /*String*/ __cdecl, ());
JASSFN(GetEventPlayerState, HANDLE /* Playerstate */ __cdecl, ());
JASSFN(GetEventTargetUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetEventUnitState, HANDLE /* Unitstate */ __cdecl, ());
JASSFN(GetExpiredTimer, HANDLE /* Timer */ __cdecl, ());
JASSFN(GetFilterDestructable, HANDLE /* Destructable */ __cdecl, ());
JASSFN(GetFilterItem, HANDLE /* Item */ __cdecl, ());
JASSFN(GetFilterPlayer, HANDLE /* Player */ __cdecl, ());
JASSFN(GetFilterUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetFloatGameState, DWFP __cdecl, (HANDLE /* Fgamestate */));
JASSFN(GetFoodMade, int __cdecl, ());
JASSFN(GetFoodUsed, int __cdecl, ());
JASSFN(GetGameDifficulty, HANDLE /* Gamedifficulty */ __cdecl, ());
JASSFN(GetGamePlacement, HANDLE /* Placement */ __cdecl, ());
JASSFN(GetGameSpeed, HANDLE /* Gamespeed */ __cdecl, ());
JASSFN(GetGameTypeSelected, HANDLE /* Gametype */ __cdecl, ());
JASSFN(GetHandleId, int __cdecl, (HANDLE /* Handle */));
JASSFN(GetHeroAgi, int __cdecl, (HANDLE /* Unit */, bool));
JASSFN(GetHeroInt, int __cdecl, (HANDLE /* Unit */, bool));
JASSFN(GetHeroLevel, int __cdecl, (HANDLE /* Unit */));
JASSFN(GetHeroProperName, HANDLE /*String*/ __cdecl, (HANDLE /* Unit */));
JASSFN(GetHeroSkillPoints, int __cdecl, (HANDLE /* Unit */));
JASSFN(GetHeroStr, int __cdecl, (HANDLE /* Unit */, bool));
JASSFN(GetHeroXP, int __cdecl, (HANDLE /* Unit */));
JASSFN(GetIntegerGameState, int __cdecl, (HANDLE /* Igamestate */));
JASSFN(GetIssuedOrderId, int __cdecl, ());
JASSFN(GetItemCharges, int __cdecl, (HANDLE /* Item */));
JASSFN(GetItemLevel, int __cdecl, (HANDLE /* Item */));
JASSFN(GetItemName, HANDLE /*String*/ __cdecl, (HANDLE /* Item */));
JASSFN(GetItemPlayer, HANDLE /* Player */ __cdecl, (HANDLE /* Item */));
JASSFN(GetItemType, HANDLE /* Itemtype */ __cdecl, (HANDLE /* Item */));
JASSFN(GetItemTypeId, int __cdecl, (HANDLE /* Item */));
JASSFN(GetItemUserData, int __cdecl, (HANDLE /* Item */));
JASSFN(GetItemX, DWFP __cdecl, (HANDLE /* Item */));
JASSFN(GetItemY, DWFP __cdecl, (HANDLE /* Item */));
JASSFN(GetKillingUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetLearnedSkill, int __cdecl, ());
JASSFN(GetLearnedSkillLevel, int __cdecl, ());
JASSFN(GetLearningUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetLeavingUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetLevelingUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetLightningColorA, DWFP __cdecl, (HANDLE /* Lightning */));
JASSFN(GetLightningColorB, DWFP __cdecl, (HANDLE /* Lightning */));
JASSFN(GetLightningColorG, DWFP __cdecl, (HANDLE /* Lightning */));
JASSFN(GetLightningColorR, DWFP __cdecl, (HANDLE /* Lightning */));
JASSFN(GetLoadedUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetLocalPlayer, HANDLE /* Player */ __cdecl, ());
JASSFN(GetLocalizedHotkey, int __cdecl, (RCString*));
JASSFN(GetLocalizedString, HANDLE /*String*/ __cdecl, (RCString*));
JASSFN(GetLocationX, DWFP __cdecl, (HANDLE /* Location */));
JASSFN(GetLocationY, DWFP __cdecl, (HANDLE /* Location */));
JASSFN(GetLocationZ, DWFP __cdecl, (HANDLE /* Location */));
JASSFN(GetManipulatedItem, HANDLE /* Item */ __cdecl, ());
JASSFN(GetManipulatingUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetObjectName, HANDLE /*String*/ __cdecl, ());
JASSFN(GetOrderPointLoc, HANDLE /* Location */ __cdecl, ());
JASSFN(GetOrderPointX, DWFP __cdecl, ());
JASSFN(GetOrderPointY, DWFP __cdecl, ());
JASSFN(GetOrderTarget, HANDLE /* Widget */ __cdecl, ());
JASSFN(GetOrderTargetDestructable, HANDLE /* Destructable */ __cdecl, ());
JASSFN(GetOrderTargetItem, HANDLE /* Item */ __cdecl, ());
JASSFN(GetOrderTargetUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetOrderedUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetOwningPlayer, HANDLE /* Player */ __cdecl, (HANDLE /* Unit */));
JASSFN(GetPlayerAlliance, bool __cdecl, (HANDLE /* Player */, HANDLE /* Player */, HANDLE /* Alliancetype */));
JASSFN(GetPlayerColor, HANDLE /* Playercolor */ __cdecl, (HANDLE /* Player */));
JASSFN(GetPlayerController, HANDLE /* Mapcontrol */ __cdecl, (HANDLE /* Player */));
JASSFN(GetPlayerHandicap, DWFP __cdecl, (HANDLE /* Player */));
JASSFN(GetPlayerHandicapXP, DWFP __cdecl, (HANDLE /* Player */));
JASSFN(GetPlayerId, int __cdecl, (HANDLE /* Player */));
JASSFN(GetPlayerName, HANDLE /*String*/ __cdecl, (HANDLE /* Player */));
JASSFN(GetPlayerRace, HANDLE /* Race */ __cdecl, (HANDLE /* Player */));
JASSFN(GetPlayerScore, int __cdecl, (HANDLE /* Player */, HANDLE /* Playerscore */));
JASSFN(GetPlayerSelectable, bool __cdecl, (HANDLE /* Player */));
JASSFN(GetPlayerSlotState, HANDLE /* Playerslotstate */ __cdecl, (HANDLE /* Player */));
JASSFN(GetPlayerStartLocation, int __cdecl, (HANDLE /* Player */));
JASSFN(GetPlayerStartLocationX, DWFP __cdecl, (HANDLE /* Player */));
JASSFN(GetPlayerStartLocationY, DWFP __cdecl, (HANDLE /* Player */));
JASSFN(GetPlayerState, int __cdecl, (HANDLE /* Player */, HANDLE /* Playerstate */));
JASSFN(GetPlayerStructureCount, int __cdecl, (HANDLE /* Player */, bool));
JASSFN(GetPlayerTaxRate, int __cdecl, (HANDLE /* Player */, HANDLE /* Player */, HANDLE /* Playerstate */));
JASSFN(GetPlayerTeam, int __cdecl, (HANDLE /* Player */));
JASSFN(GetPlayerTechCount, int __cdecl, (HANDLE /* Player */, int, bool));
JASSFN(GetPlayerTechMaxAllowed, int __cdecl, (HANDLE /* Player */, int));
JASSFN(GetPlayerTechResearched, bool __cdecl, (HANDLE /* Player */, int, bool));
JASSFN(GetPlayerTypedUnitCount, int __cdecl, (HANDLE /* Player */, RCString*, bool, bool));
JASSFN(GetPlayerUnitCount, int __cdecl, (HANDLE /* Player */, bool));
JASSFN(GetPlayers, int __cdecl, ());
JASSFN(GetRandomInt, int __cdecl, (int, int));
JASSFN(GetRandomReal, DWFP __cdecl, (float*, float*));
JASSFN(GetRectCenterX, DWFP __cdecl, (HANDLE /* Rect */));
JASSFN(GetRectCenterY, DWFP __cdecl, (HANDLE /* Rect */));
JASSFN(GetRectMaxX, DWFP __cdecl, (HANDLE /* Rect */));
JASSFN(GetRectMaxY, DWFP __cdecl, (HANDLE /* Rect */));
JASSFN(GetRectMinX, DWFP __cdecl, (HANDLE /* Rect */));
JASSFN(GetRectMinY, DWFP __cdecl, (HANDLE /* Rect */));
JASSFN(GetRescuer, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetResearched, int __cdecl, ());
JASSFN(GetResearchingUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetResourceAmount, int __cdecl, (HANDLE /* Unit */));
JASSFN(GetResourceDensity, HANDLE /* Mapdensity */ __cdecl, ());
JASSFN(GetRevivableUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetRevivingUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetSaveBasicFilename, HANDLE /*String*/ __cdecl, ());
JASSFN(GetSellingUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetSoldItem, HANDLE /* Item */ __cdecl, ());
JASSFN(GetSoldUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetSoundDuration, int __cdecl, (HANDLE /* Sound */));
JASSFN(GetSoundFileDuration, int __cdecl, (RCString*));
JASSFN(GetSoundIsLoading, bool __cdecl, (HANDLE /* Sound */));
JASSFN(GetSoundIsPlaying, bool __cdecl, (HANDLE /* Sound */));
JASSFN(GetSpellAbility, HANDLE /* Ability */ __cdecl, ());
JASSFN(GetSpellAbilityId, int __cdecl, ());
JASSFN(GetSpellAbilityUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetSpellTargetDestructable, HANDLE /* Destructable */ __cdecl, ());
JASSFN(GetSpellTargetItem, HANDLE /* Item */ __cdecl, ());
JASSFN(GetSpellTargetLoc, HANDLE /* Location */ __cdecl, ());
JASSFN(GetSpellTargetUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetSpellTargetX, DWFP __cdecl, ());
JASSFN(GetSpellTargetY, DWFP __cdecl, ());
JASSFN(GetStartLocPrio, HANDLE /* Startlocprio */ __cdecl, (int, int));
JASSFN(GetStartLocPrioSlot, int __cdecl, (int, int));
JASSFN(GetStartLocationLoc, HANDLE /* Location */ __cdecl, ());
JASSFN(GetStartLocationX, DWFP __cdecl, ());
JASSFN(GetStartLocationY, DWFP __cdecl, ());
JASSFN(GetStoredBoolean, bool __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*));
JASSFN(GetStoredInteger, int __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*));
JASSFN(GetStoredReal, DWFP __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*));
JASSFN(GetStoredString, HANDLE /*String*/ __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*));
JASSFN(GetSummonedUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetSummoningUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetTeams, int __cdecl, ());
JASSFN(GetTerrainCliffLevel, int __cdecl, (float*, float*));
JASSFN(GetTerrainType, int __cdecl, (float*, float*));
JASSFN(GetTerrainVariance, int __cdecl, (float*, float*));
JASSFN(GetTimeOfDayScale, DWFP __cdecl, ());
JASSFN(GetTournamentFinishNowPlayer, HANDLE /* Player */ __cdecl, ());
JASSFN(GetTournamentFinishNowRule, HANDLE /*  */ __cdecl, ());
JASSFN(GetTournamentFinishSoonTimeRemaining, HANDLE /*  */ __cdecl, ());
JASSFN(GetTournamentScore, int __cdecl, (HANDLE /* Player */));
JASSFN(GetTrainedUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetTrainedUnitType, int __cdecl, ());
JASSFN(GetTransportUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetTriggerDestructable, HANDLE /* Destructable */ __cdecl, ());
JASSFN(GetTriggerEvalCount, int __cdecl, (HANDLE /* Trigger */));
JASSFN(GetTriggerEventId, HANDLE /* Eventid */ __cdecl, ());
JASSFN(GetTriggerExecCount, int __cdecl, (HANDLE /* Trigger */));
JASSFN(GetTriggerPlayer, HANDLE /* Player */ __cdecl, ());
JASSFN(GetTriggerUnit, HANDLE /* Unit */ __cdecl, ());
JASSFN(GetTriggerWidget, HANDLE /* Widget */ __cdecl, ());
JASSFN(GetTriggeringRegion, HANDLE /* Region */ __cdecl, ());
JASSFN(GetTriggeringTrackable, HANDLE /* Trackable */ __cdecl, ());
JASSFN(GetTriggeringTrigger, HANDLE /* Trigger */ __cdecl, ());
JASSFN(GetUnitAbilityLevel, int __cdecl, (HANDLE /* Unit */, int));
JASSFN(GetUnitAcquireRange, DWFP __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitCurrentOrder, int __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitDefaultAcquireRange, DWFP __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitDefaultFlyHeight, DWFP __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitDefaultMoveSpeed, DWFP __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitDefaultPropWindow, DWFP __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitDefaultTurnSpeed, DWFP __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitFacing, DWFP __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitFlyHeight, DWFP __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitFoodMade, int __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitFoodUsed, int __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitLevel, int __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitLoc, HANDLE /* Location */ __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitMoveSpeed, DWFP __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitName, HANDLE /*String*/ __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitPointValue, int __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitPointValueByType, int __cdecl, ());
JASSFN(GetUnitPropWindow, DWFP __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitRace, HANDLE /* Race */ __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitRallyDestructable, HANDLE /* Destructable */ __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitRallyPoint, HANDLE /* Location */ __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitRallyUnit, HANDLE /* Unit */ __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitState, DWFP __cdecl, (HANDLE /* Unit */, HANDLE /* Unitstate */));
JASSFN(GetUnitTurnSpeed, DWFP __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitTypeId, int __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitUserData, int __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitX, DWFP __cdecl, (HANDLE /* Unit */));
JASSFN(GetUnitY, DWFP __cdecl, (HANDLE /* Unit */));
JASSFN(GetWidgetLife, DWFP __cdecl, (HANDLE /* Widget */));
JASSFN(GetWidgetX, DWFP __cdecl, (HANDLE /* Widget */));
JASSFN(GetWidgetY, DWFP __cdecl, (HANDLE /* Widget */));
JASSFN(GetWinningPlayer, HANDLE /* Player */ __cdecl, ());
JASSFN(GetWorldBounds, HANDLE /* Rect */ __cdecl, ());
JASSFN(GroupAddUnit, void __cdecl, (HANDLE /* Group */, HANDLE /* Unit */));
JASSFN(GroupClear, void __cdecl, (HANDLE /* Group */));
JASSFN(GroupEnumUnitsInRange, void __cdecl, (HANDLE /* Group */, float*, float*, float*, HANDLE /* Boolexpr */));
JASSFN(GroupEnumUnitsInRangeCounted, void __cdecl, (HANDLE /* Group */, float*, float*, float*, HANDLE /* Boolexpr */, int));
JASSFN(GroupEnumUnitsInRangeOfLoc, void __cdecl, (HANDLE /* Group */, HANDLE /* Location */, float*, HANDLE /* Boolexpr */));
JASSFN(GroupEnumUnitsInRangeOfLocCounted, void __cdecl, (HANDLE /* Group */, HANDLE /* Location */, float*, HANDLE /* Boolexpr */, int));
JASSFN(GroupEnumUnitsInRect, void __cdecl, (HANDLE /* Group */, HANDLE /* Rect */, HANDLE /* Boolexpr */));
JASSFN(GroupEnumUnitsInRectCounted, void __cdecl, (HANDLE /* Group */, HANDLE /* Rect */, HANDLE /* Boolexpr */, int));
JASSFN(GroupEnumUnitsOfPlayer, void __cdecl, (HANDLE /* Group */, HANDLE /* Player */, HANDLE /* Boolexpr */));
JASSFN(GroupEnumUnitsOfType, void __cdecl, (HANDLE /* Group */, RCString*, HANDLE /* Boolexpr */));
JASSFN(GroupEnumUnitsOfTypeCounted, void __cdecl, (HANDLE /* Group */, RCString*, HANDLE /* Boolexpr */, int));
JASSFN(GroupEnumUnitsSelected, void __cdecl, (HANDLE /* Group */, HANDLE /* Player */, HANDLE /* Boolexpr */));
JASSFN(GroupImmediateOrder, bool __cdecl, (HANDLE /* Group */, RCString*));
JASSFN(GroupImmediateOrderById, bool __cdecl, (HANDLE /* Group */, int));
JASSFN(GroupPointOrder, bool __cdecl, (HANDLE /* Group */, RCString*, float*, float*));
JASSFN(GroupPointOrderById, bool __cdecl, (HANDLE /* Group */, int, float*, float*));
JASSFN(GroupPointOrderByIdLoc, bool __cdecl, (HANDLE /* Group */, int, HANDLE /* Location */));
JASSFN(GroupPointOrderLoc, bool __cdecl, (HANDLE /* Group */, RCString*, HANDLE /* Location */));
JASSFN(GroupRemoveUnit, void __cdecl, (HANDLE /* Group */, HANDLE /* Unit */));
JASSFN(GroupTargetOrder, bool __cdecl, (HANDLE /* Group */, RCString*, HANDLE /* Widget */));
JASSFN(GroupTargetOrderById, bool __cdecl, (HANDLE /* Group */, int, HANDLE /* Widget */));
JASSFN(HaveSavedBoolean, bool __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(HaveSavedHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(HaveSavedInteger, bool __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(HaveSavedReal, bool __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(HaveSavedString, bool __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(HaveStoredBoolean, bool __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*));
JASSFN(HaveStoredInteger, bool __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*));
JASSFN(HaveStoredReal, bool __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*));
JASSFN(HaveStoredString, bool __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*));
JASSFN(HaveStoredUnit, bool __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*));
JASSFN(I2R, DWFP __cdecl, ());
JASSFN(I2S, HANDLE /*String*/ __cdecl, ());
JASSFN(IncUnitAbilityLevel, int __cdecl, (HANDLE /* Unit */, int));
JASSFN(InitGameCache, HANDLE /* Gamecache */ __cdecl, (RCString*));
JASSFN(InitHashtable, HANDLE /* Hashtable */ __cdecl, ());
JASSFN(IsCineFilterDisplayed, bool __cdecl, ());
JASSFN(IsDestructableInvulnerable, bool __cdecl, (HANDLE /* Destructable */));
JASSFN(IsFogEnabled, bool __cdecl, ());
JASSFN(IsFogMaskEnabled, bool __cdecl, ());
JASSFN(IsFoggedToPlayer, bool __cdecl, (float*, float*, HANDLE /* Player */));
JASSFN(IsGameTypeSupported, bool __cdecl, (HANDLE /* Gametype */));
JASSFN(IsHeroUnitId, bool __cdecl, ());
JASSFN(IsItemIdPawnable, bool __cdecl, ());
JASSFN(IsItemIdPowerup, bool __cdecl, ());
JASSFN(IsItemIdSellable, bool __cdecl, ());
JASSFN(IsItemInvulnerable, bool __cdecl, (HANDLE /* Item */));
JASSFN(IsItemOwned, bool __cdecl, (HANDLE /* Item */));
JASSFN(IsItemPawnable, bool __cdecl, (HANDLE /* Item */));
JASSFN(IsItemPowerup, bool __cdecl, (HANDLE /* Item */));
JASSFN(IsItemSellable, bool __cdecl, (HANDLE /* Item */));
JASSFN(IsItemVisible, bool __cdecl, (HANDLE /* Item */));
JASSFN(IsLeaderboardDisplayed, bool __cdecl, (HANDLE /* Leaderboard */));
JASSFN(IsLocationFoggedToPlayer, bool __cdecl, (HANDLE /* Location */, HANDLE /* Player */));
JASSFN(IsLocationInRegion, bool __cdecl, (HANDLE /* Region */, HANDLE /* Location */));
JASSFN(IsLocationMaskedToPlayer, bool __cdecl, (HANDLE /* Location */, HANDLE /* Player */));
JASSFN(IsLocationVisibleToPlayer, bool __cdecl, (HANDLE /* Location */, HANDLE /* Player */));
JASSFN(IsMapFlagSet, bool __cdecl, (HANDLE /* Mapflag */));
JASSFN(IsMaskedToPlayer, bool __cdecl, (float*, float*, HANDLE /* Player */));
JASSFN(IsMultiboardDisplayed, bool __cdecl, (HANDLE /* Multiboard */));
JASSFN(IsMultiboardMinimized, bool __cdecl, (HANDLE /* Multiboard */));
JASSFN(IsNoDefeatCheat, bool __cdecl, ());
JASSFN(IsNoVictoryCheat, bool __cdecl, ());
JASSFN(IsPlayerAlly, bool __cdecl, (HANDLE /* Player */, HANDLE /* Player */));
JASSFN(IsPlayerEnemy, bool __cdecl, (HANDLE /* Player */, HANDLE /* Player */));
JASSFN(IsPlayerInForce, bool __cdecl, (HANDLE /* Player */, HANDLE /* Force */));
JASSFN(IsPlayerObserver, bool __cdecl, (HANDLE /* Player */));
JASSFN(IsPlayerRacePrefSet, bool __cdecl, (HANDLE /* Player */, HANDLE /* Racepreference */));
JASSFN(IsPointBlighted, bool __cdecl, (float*, float*));
JASSFN(IsPointInRegion, bool __cdecl, (HANDLE /* Region */, float*, float*));
JASSFN(IsQuestCompleted, bool __cdecl, (HANDLE /* Quest */));
JASSFN(IsQuestDiscovered, bool __cdecl, (HANDLE /* Quest */));
JASSFN(IsQuestEnabled, bool __cdecl, (HANDLE /* Quest */));
JASSFN(IsQuestFailed, bool __cdecl, (HANDLE /* Quest */));
JASSFN(IsQuestItemCompleted, bool __cdecl, (HANDLE /* Questitem */));
JASSFN(IsQuestRequired, bool __cdecl, (HANDLE /* Quest */));
JASSFN(IsSuspendedXP, bool __cdecl, (HANDLE /* Unit */));
JASSFN(IsTerrainPathable, bool __cdecl, (float*, float*, HANDLE /* Pathingtype */));
JASSFN(IsTimerDialogDisplayed, bool __cdecl, (HANDLE /* Timerdialog */));
JASSFN(IsTriggerEnabled, bool __cdecl, (HANDLE /* Trigger */));
JASSFN(IsTriggerWaitOnSleeps, bool __cdecl, (HANDLE /* Trigger */));
JASSFN(IsUnit, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Unit */));
JASSFN(IsUnitAlly, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Player */));
JASSFN(IsUnitDetected, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Player */));
JASSFN(IsUnitEnemy, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Player */));
JASSFN(IsUnitFogged, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Player */));
JASSFN(IsUnitHidden, bool __cdecl, (HANDLE /* Unit */));
JASSFN(IsUnitIdType, bool __cdecl, (int, HANDLE /* Unittype */));
JASSFN(IsUnitIllusion, bool __cdecl, (HANDLE /* Unit */));
JASSFN(IsUnitInForce, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Force */));
JASSFN(IsUnitInGroup, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Group */));
JASSFN(IsUnitInRange, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Unit */, float*));
JASSFN(IsUnitInRangeLoc, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Location */, float*));
JASSFN(IsUnitInRangeXY, bool __cdecl, (HANDLE /* Unit */, float*, float*, float*));
JASSFN(IsUnitInRegion, bool __cdecl, (HANDLE /* Region */, HANDLE /* Unit */));
JASSFN(IsUnitInTransport, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Unit */));
JASSFN(IsUnitInvisible, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Player */));
JASSFN(IsUnitLoaded, bool __cdecl, (HANDLE /* Unit */));
JASSFN(IsUnitMasked, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Player */));
JASSFN(IsUnitOwnedByPlayer, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Player */));
JASSFN(IsUnitPaused, bool __cdecl, (HANDLE /* Unit */));
JASSFN(IsUnitRace, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Race */));
JASSFN(IsUnitSelected, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Player */));
JASSFN(IsUnitType, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Unittype */));
JASSFN(IsUnitVisible, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Player */));
JASSFN(IsVisibleToPlayer, bool __cdecl, (float*, float*, HANDLE /* Player */));
JASSFN(IssueBuildOrder, bool __cdecl, (HANDLE /* Unit */, RCString*, float*, float*));
JASSFN(IssueBuildOrderById, bool __cdecl, (HANDLE /* Unit */, int, float*, float*));
JASSFN(IssueImmediateOrder, bool __cdecl, (HANDLE /* Unit */, RCString*));
JASSFN(IssueImmediateOrderById, bool __cdecl, (HANDLE /* Unit */, int));
JASSFN(IssueInstantPointOrder, bool __cdecl, (HANDLE /* Unit */, RCString*, float*, float*, HANDLE /* Widget */));
JASSFN(IssueInstantPointOrderById, bool __cdecl, (HANDLE /* Unit */, int, float*, float*, HANDLE /* Widget */));
JASSFN(IssueInstantTargetOrder, bool __cdecl, (HANDLE /* Unit */, RCString*, HANDLE /* Widget */, HANDLE /* Widget */));
JASSFN(IssueInstantTargetOrderById, bool __cdecl, (HANDLE /* Unit */, int, HANDLE /* Widget */, HANDLE /* Widget */));
JASSFN(IssueNeutralImmediateOrder, bool __cdecl, (HANDLE /* Player */, HANDLE /* Unit */, RCString*));
JASSFN(IssueNeutralImmediateOrderById, bool __cdecl, (HANDLE /* Player */, HANDLE /* Unit */, int));
JASSFN(IssueNeutralPointOrder, bool __cdecl, (HANDLE /* Player */, HANDLE /* Unit */, RCString*, float*, float*));
JASSFN(IssueNeutralPointOrderById, bool __cdecl, (HANDLE /* Player */, HANDLE /* Unit */, int, float*, float*));
JASSFN(IssueNeutralTargetOrder, bool __cdecl, (HANDLE /* Player */, HANDLE /* Unit */, RCString*, HANDLE /* Widget */));
JASSFN(IssueNeutralTargetOrderById, bool __cdecl, (HANDLE /* Player */, HANDLE /* Unit */, int, HANDLE /* Widget */));
JASSFN(IssuePointOrder, bool __cdecl, (HANDLE /* Unit */, RCString*, float*, float*));
JASSFN(IssuePointOrderById, bool __cdecl, (HANDLE /* Unit */, int, float*, float*));
JASSFN(IssuePointOrderByIdLoc, bool __cdecl, (HANDLE /* Unit */, int, HANDLE /* Location */));
JASSFN(IssuePointOrderLoc, bool __cdecl, (HANDLE /* Unit */, RCString*, HANDLE /* Location */));
JASSFN(IssueTargetOrder, bool __cdecl, (HANDLE /* Unit */, RCString*, HANDLE /* Widget */));
JASSFN(IssueTargetOrderById, bool __cdecl, (HANDLE /* Unit */, int, HANDLE /* Widget */));
JASSFN(ItemPoolAddItemType, void __cdecl, (HANDLE /* Itempool */, int, float*));
JASSFN(ItemPoolRemoveItemType, void __cdecl, (HANDLE /* Itempool */, int));
JASSFN(KillDestructable, void __cdecl, (HANDLE /* Destructable */));
JASSFN(KillSoundWhenDone, void __cdecl, (HANDLE /* Sound */));
JASSFN(KillUnit, void __cdecl, (HANDLE /* Unit */));
JASSFN(LeaderboardAddItem, void __cdecl, (HANDLE /* Leaderboard */, RCString*, int, HANDLE /* Player */));
JASSFN(LeaderboardClear, void __cdecl, (HANDLE /* Leaderboard */));
JASSFN(LeaderboardDisplay, void __cdecl, (HANDLE /* Leaderboard */, bool));
JASSFN(LeaderboardGetItemCount, int __cdecl, (HANDLE /* Leaderboard */));
JASSFN(LeaderboardGetLabelText, HANDLE /*String*/ __cdecl, (HANDLE /* Leaderboard */));
JASSFN(LeaderboardGetPlayerIndex, int __cdecl, (HANDLE /* Leaderboard */, HANDLE /* Player */));
JASSFN(LeaderboardHasPlayerItem, bool __cdecl, (HANDLE /* Leaderboard */, HANDLE /* Player */));
JASSFN(LeaderboardRemoveItem, void __cdecl, (HANDLE /* Leaderboard */, int));
JASSFN(LeaderboardRemovePlayerItem, void __cdecl, (HANDLE /* Leaderboard */, HANDLE /* Player */));
JASSFN(LeaderboardSetItemLabel, void __cdecl, (HANDLE /* Leaderboard */, int, RCString*));
JASSFN(LeaderboardSetItemLabelColor, void __cdecl, (HANDLE /* Leaderboard */, int, int, int, int, int));
JASSFN(LeaderboardSetItemStyle, void __cdecl, (HANDLE /* Leaderboard */, int, bool, bool, bool));
JASSFN(LeaderboardSetItemValue, void __cdecl, (HANDLE /* Leaderboard */, int, int));
JASSFN(LeaderboardSetItemValueColor, void __cdecl, (HANDLE /* Leaderboard */, int, int, int, int, int));
JASSFN(LeaderboardSetLabel, void __cdecl, (HANDLE /* Leaderboard */, RCString*));
JASSFN(LeaderboardSetLabelColor, void __cdecl, (HANDLE /* Leaderboard */, int, int, int, int));
JASSFN(LeaderboardSetSizeByItemCount, void __cdecl, (HANDLE /* Leaderboard */, int));
JASSFN(LeaderboardSetStyle, void __cdecl, (HANDLE /* Leaderboard */, bool, bool, bool, bool));
JASSFN(LeaderboardSetValueColor, void __cdecl, (HANDLE /* Leaderboard */, int, int, int, int));
JASSFN(LeaderboardSortItemsByLabel, void __cdecl, (HANDLE /* Leaderboard */, bool));
JASSFN(LeaderboardSortItemsByPlayer, void __cdecl, (HANDLE /* Leaderboard */, bool));
JASSFN(LeaderboardSortItemsByValue, void __cdecl, (HANDLE /* Leaderboard */, bool));
JASSFN(LoadAbilityHandle, HANDLE /* Ability */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadBoolean, HANDLE /*  */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadBooleanExprHandle, HANDLE /* Boolexpr */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadButtonHandle, HANDLE /* Button */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadDefeatConditionHandle, HANDLE /* Defeatcondition */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadDestructableHandle, HANDLE /* Destructable */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadDialogHandle, HANDLE /* Dialog */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadEffectHandle, HANDLE /* Effect */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadFogModifierHandle, HANDLE /* Fogmodifier */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadFogStateHandle, HANDLE /* Fogstate */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadForceHandle, HANDLE /* Force */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadGame, void __cdecl, (RCString*, bool));
JASSFN(LoadGroupHandle, HANDLE /* Group */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadHashtableHandle, HANDLE /* Hashtable */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadImageHandle, HANDLE /* Image */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadInteger, HANDLE /*  */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadItemHandle, HANDLE /* Item */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadItemPoolHandle, HANDLE /* Itempool */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadLeaderboardHandle, HANDLE /* Leaderboard */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadLightningHandle, HANDLE /* Lightning */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadLocationHandle, HANDLE /* Location */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadMultiboardHandle, HANDLE /* Multiboard */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadMultiboardItemHandle, HANDLE /* Multiboarditem */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadPlayerHandle, HANDLE /* Player */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadQuestHandle, HANDLE /* Quest */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadQuestItemHandle, HANDLE /* Questitem */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadReal, HANDLE /*  */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadRectHandle, HANDLE /* Rect */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadRegionHandle, HANDLE /* Region */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadSoundHandle, HANDLE /* Sound */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadStr, HANDLE /*  */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadTextTagHandle, HANDLE /* Texttag */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadTimerDialogHandle, HANDLE /* Timerdialog */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadTimerHandle, HANDLE /* Timer */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadTrackableHandle, HANDLE /* Trackable */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadTriggerActionHandle, HANDLE /* Triggeraction */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadTriggerConditionHandle, HANDLE /* Triggercondition */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadTriggerEventHandle, HANDLE /* Event */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadTriggerHandle, HANDLE /* Trigger */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadUbersplatHandle, HANDLE /* Ubersplat */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadUnitHandle, HANDLE /* Unit */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadUnitPoolHandle, HANDLE /* Unitpool */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(LoadWidgetHandle, HANDLE /* Widget */ __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(Location, HANDLE /* Location */ __cdecl, (float*, float*));
JASSFN(MoveLightning, bool __cdecl, (HANDLE /* Lightning */, bool, float*, float*, float*, float*));
JASSFN(MoveLightningEx, bool __cdecl, (HANDLE /* Lightning */, bool, float*, float*, float*, float*, float*, float*));
JASSFN(MoveLocation, void __cdecl, (HANDLE /* Location */, float*, float*));
JASSFN(MoveRectTo, void __cdecl, (HANDLE /* Rect */, float*, float*));
JASSFN(MoveRectToLoc, void __cdecl, (HANDLE /* Rect */, HANDLE /* Location */));
JASSFN(MultiboardClear, void __cdecl, (HANDLE /* Multiboard */));
JASSFN(MultiboardDisplay, void __cdecl, (HANDLE /* Multiboard */, bool));
JASSFN(MultiboardGetColumnCount, int __cdecl, (HANDLE /* Multiboard */));
JASSFN(MultiboardGetItem, HANDLE /* Multiboarditem */ __cdecl, (HANDLE /* Multiboard */, int, int));
JASSFN(MultiboardGetRowCount, int __cdecl, (HANDLE /* Multiboard */));
JASSFN(MultiboardGetTitleText, HANDLE /*String*/ __cdecl, (HANDLE /* Multiboard */));
JASSFN(MultiboardMinimize, void __cdecl, (HANDLE /* Multiboard */, bool));
JASSFN(MultiboardReleaseItem, void __cdecl, (HANDLE /* Multiboarditem */));
JASSFN(MultiboardSetColumnCount, void __cdecl, (HANDLE /* Multiboard */, int));
JASSFN(MultiboardSetItemIcon, void __cdecl, (HANDLE /* Multiboarditem */, RCString*));
JASSFN(MultiboardSetItemStyle, void __cdecl, (HANDLE /* Multiboarditem */, bool, bool));
JASSFN(MultiboardSetItemValue, void __cdecl, (HANDLE /* Multiboarditem */, RCString*));
JASSFN(MultiboardSetItemValueColor, void __cdecl, (HANDLE /* Multiboarditem */, int, int, int, int));
JASSFN(MultiboardSetItemWidth, void __cdecl, (HANDLE /* Multiboarditem */, float*));
JASSFN(MultiboardSetItemsIcon, void __cdecl, (HANDLE /* Multiboard */, RCString*));
JASSFN(MultiboardSetItemsStyle, void __cdecl, (HANDLE /* Multiboard */, bool, bool));
JASSFN(MultiboardSetItemsValue, void __cdecl, (HANDLE /* Multiboard */, RCString*));
JASSFN(MultiboardSetItemsValueColor, void __cdecl, (HANDLE /* Multiboard */, int, int, int, int));
JASSFN(MultiboardSetItemsWidth, void __cdecl, (HANDLE /* Multiboard */, float*));
JASSFN(MultiboardSetRowCount, void __cdecl, (HANDLE /* Multiboard */, int));
JASSFN(MultiboardSetTitleText, void __cdecl, (HANDLE /* Multiboard */, RCString*));
JASSFN(MultiboardSetTitleTextColor, void __cdecl, (HANDLE /* Multiboard */, int, int, int, int));
JASSFN(MultiboardSuppressDisplay, void __cdecl, ());
JASSFN(NewSoundEnvironment, void __cdecl, (RCString*));
JASSFN(Not, HANDLE /* Boolexpr */ __cdecl, (HANDLE /* Boolexpr */));
JASSFN(Or, HANDLE /* Boolexpr */ __cdecl, (HANDLE /* Boolexpr */, HANDLE /* Boolexpr */));
JASSFN(OrderId, int __cdecl, (RCString*));
JASSFN(OrderId2String, HANDLE /*String*/ __cdecl, ());
JASSFN(PanCameraTo, void __cdecl, (float*, float*));
JASSFN(PanCameraToTimed, void __cdecl, (float*, float*, float*));
JASSFN(PanCameraToTimedWithZ, void __cdecl, (float*, float*, float*, float*));
JASSFN(PanCameraToWithZ, void __cdecl, (float*, float*, float*));
JASSFN(PauseCompAI, void __cdecl, (HANDLE /* Player */, bool));
JASSFN(PauseGame, void __cdecl, ());
JASSFN(PauseTimer, void __cdecl, (HANDLE /* Timer */));
JASSFN(PauseUnit, void __cdecl, (HANDLE /* Unit */, bool));
JASSFN(PingMinimap, void __cdecl, (float*, float*, float*));
JASSFN(PingMinimapEx, void __cdecl, (float*, float*, float*, int, int, int, bool));
JASSFN(PlaceRandomItem, HANDLE /* Item */ __cdecl, (HANDLE /* Itempool */, float*, float*));
JASSFN(PlaceRandomUnit, HANDLE /* Unit */ __cdecl, (HANDLE /* Unitpool */, HANDLE /* Player */, float*, float*, float*));
JASSFN(PlayCinematic, void __cdecl, (RCString*));
JASSFN(PlayModelCinematic, void __cdecl, (RCString*));
JASSFN(PlayMusic, void __cdecl, (RCString*));
JASSFN(PlayMusicEx, void __cdecl, (RCString*, int, int));
JASSFN(PlayThematicMusic, void __cdecl, (RCString*));
JASSFN(PlayThematicMusicEx, void __cdecl, (RCString*, int));
JASSFN(Player, HANDLE /* Player */ __cdecl, (int));
JASSFN(PlayerGetLeaderboard, HANDLE /* Leaderboard */ __cdecl, (HANDLE /* Player */));
JASSFN(PlayerSetLeaderboard, void __cdecl, (HANDLE /* Player */, HANDLE /* Leaderboard */));
JASSFN(Pow, DWFP __cdecl, (float*, float*));
JASSFN(Preload, void __cdecl, (RCString*));
JASSFN(PreloadEnd, void __cdecl, (float*));
JASSFN(PreloadEndEx, void __cdecl, ());
JASSFN(PreloadGenClear, void __cdecl, ());
JASSFN(PreloadGenEnd, void __cdecl, (RCString*));
JASSFN(PreloadGenStart, void __cdecl, ());
JASSFN(PreloadRefresh, void __cdecl, ());
JASSFN(PreloadStart, void __cdecl, ());
JASSFN(Preloader, void __cdecl, (RCString*));
JASSFN(QuestCreateItem, HANDLE /* Questitem */ __cdecl, (HANDLE /* Quest */));
JASSFN(QuestItemSetCompleted, void __cdecl, (HANDLE /* Questitem */, bool));
JASSFN(QuestItemSetDescription, void __cdecl, (HANDLE /* Questitem */, RCString*));
JASSFN(QuestSetCompleted, void __cdecl, (HANDLE /* Quest */, bool));
JASSFN(QuestSetDescription, void __cdecl, (HANDLE /* Quest */, RCString*));
JASSFN(QuestSetDiscovered, void __cdecl, (HANDLE /* Quest */, bool));
JASSFN(QuestSetEnabled, void __cdecl, (HANDLE /* Quest */, bool));
JASSFN(QuestSetFailed, void __cdecl, (HANDLE /* Quest */, bool));
JASSFN(QuestSetIconPath, void __cdecl, (HANDLE /* Quest */, RCString*));
JASSFN(QuestSetRequired, void __cdecl, (HANDLE /* Quest */, bool));
JASSFN(QuestSetTitle, void __cdecl, (HANDLE /* Quest */, RCString*));
JASSFN(QueueDestructableAnimation, void __cdecl, (HANDLE /* Destructable */, RCString*));
JASSFN(QueueUnitAnimation, void __cdecl, (HANDLE /* Unit */, RCString*));
JASSFN(R2I, int __cdecl, (float*));
JASSFN(R2S, HANDLE /*String*/ __cdecl, (float*));
JASSFN(R2SW, HANDLE /*String*/ __cdecl, (float*, int, int));
JASSFN(Rad2Deg, DWFP __cdecl, (float*));
JASSFN(Rect, HANDLE /* Rect */ __cdecl, (float*, float*, float*, float*));
JASSFN(RectFromLoc, HANDLE /* Rect */ __cdecl, (HANDLE /* Location */, HANDLE /* Location */));
JASSFN(RecycleGuardPosition, void __cdecl, (HANDLE /* Unit */));
JASSFN(RegionAddCell, void __cdecl, (HANDLE /* Region */, float*, float*));
JASSFN(RegionAddCellAtLoc, void __cdecl, (HANDLE /* Region */, HANDLE /* Location */));
JASSFN(RegionAddRect, void __cdecl, (HANDLE /* Region */, HANDLE /* Rect */));
JASSFN(RegionClearCell, void __cdecl, (HANDLE /* Region */, float*, float*));
JASSFN(RegionClearCellAtLoc, void __cdecl, (HANDLE /* Region */, HANDLE /* Location */));
JASSFN(RegionClearRect, void __cdecl, (HANDLE /* Region */, HANDLE /* Rect */));
JASSFN(RegisterStackedSound, void __cdecl, (HANDLE /* Sound */, bool, float*, float*));
JASSFN(ReloadGame, void __cdecl, ());
JASSFN(ReloadGameCachesFromDisk, bool __cdecl, ());
JASSFN(RemoveAllGuardPositions, void __cdecl, (HANDLE /* Player */));
JASSFN(RemoveDestructable, void __cdecl, (HANDLE /* Destructable */));
JASSFN(RemoveGuardPosition, void __cdecl, (HANDLE /* Unit */));
JASSFN(RemoveItem, void __cdecl, (HANDLE /* Item */));
JASSFN(RemoveItemFromAllStock, void __cdecl, ());
JASSFN(RemoveItemFromStock, void __cdecl, (HANDLE /* Unit */, int));
JASSFN(RemoveLocation, void __cdecl, (HANDLE /* Location */));
JASSFN(RemovePlayer, void __cdecl, (HANDLE /* Player */, HANDLE /* Playergameresult */));
JASSFN(RemoveRect, void __cdecl, (HANDLE /* Rect */));
JASSFN(RemoveRegion, void __cdecl, (HANDLE /* Region */));
JASSFN(RemoveSaveDirectory, bool __cdecl, (RCString*));
JASSFN(RemoveSavedBoolean, void __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(RemoveSavedHandle, void __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(RemoveSavedInteger, void __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(RemoveSavedReal, void __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(RemoveSavedString, void __cdecl, (HANDLE /* Hashtable */, int, int));
JASSFN(RemoveUnit, void __cdecl, (HANDLE /* Unit */));
JASSFN(RemoveUnitFromAllStock, void __cdecl, ());
JASSFN(RemoveUnitFromStock, void __cdecl, (HANDLE /* Unit */, int));
JASSFN(RemoveWeatherEffect, void __cdecl, (HANDLE /* Weathereffect */));
JASSFN(RenameSaveDirectory, bool __cdecl, (RCString*, RCString*));
JASSFN(ResetTerrainFog, void __cdecl, ());
JASSFN(ResetToGameCamera, void __cdecl, (float*));
JASSFN(ResetTrigger, void __cdecl, (HANDLE /* Trigger */));
JASSFN(ResetUbersplat, void __cdecl, (HANDLE /* Ubersplat */));
JASSFN(ResetUnitLookAt, void __cdecl, (HANDLE /* Unit */));
JASSFN(RestartGame, void __cdecl, ());
JASSFN(RestoreUnit, HANDLE /* Unit */ __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*, HANDLE /* Player */, float*, float*, float*));
JASSFN(ResumeMusic, void __cdecl, ());
JASSFN(ResumeTimer, void __cdecl, (HANDLE /* Timer */));
JASSFN(ReviveHero, bool __cdecl, (HANDLE /* Unit */, float*, float*, bool));
JASSFN(ReviveHeroLoc, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Location */, bool));
JASSFN(S2I, int __cdecl, (RCString*));
JASSFN(S2R, DWFP __cdecl, (RCString*));
JASSFN(SaveAbilityHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Ability */));
JASSFN(SaveAgentHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Agent */));
JASSFN(SaveBoolean, void __cdecl, (HANDLE /* Hashtable */, int, int, bool));
JASSFN(SaveBooleanExprHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Boolexpr */));
JASSFN(SaveButtonHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Button */));
JASSFN(SaveDefeatConditionHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Defeatcondition */));
JASSFN(SaveDestructableHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Destructable */));
JASSFN(SaveDialogHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Dialog */));
JASSFN(SaveEffectHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Effect */));
JASSFN(SaveFogModifierHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Fogmodifier */));
JASSFN(SaveFogStateHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Fogstate */));
JASSFN(SaveForceHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Force */));
JASSFN(SaveGame, void __cdecl, (RCString*));
JASSFN(SaveGameCache, bool __cdecl, (HANDLE /* Gamecache */));
JASSFN(SaveGameExists, bool __cdecl, (RCString*));
JASSFN(SaveGroupHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Group */));
JASSFN(SaveHashtableHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Hashtable */));
JASSFN(SaveImageHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Image */));
JASSFN(SaveInteger, void __cdecl, (HANDLE /* Hashtable */, int, int, int));
JASSFN(SaveItemHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Item */));
JASSFN(SaveItemPoolHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Itempool */));
JASSFN(SaveLeaderboardHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Leaderboard */));
JASSFN(SaveLightningHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Lightning */));
JASSFN(SaveLocationHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Location */));
JASSFN(SaveMultiboardHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Multiboard */));
JASSFN(SaveMultiboardItemHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Multiboarditem */));
JASSFN(SavePlayerHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Player */));
JASSFN(SaveQuestHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Quest */));
JASSFN(SaveQuestItemHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Questitem */));
JASSFN(SaveReal, void __cdecl, (HANDLE /* Hashtable */, int, int, float*));
JASSFN(SaveRectHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Rect */));
JASSFN(SaveRegionHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Region */));
JASSFN(SaveSoundHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Sound */));
JASSFN(SaveStr, bool __cdecl, (HANDLE /* Hashtable */, int, int, RCString*));
JASSFN(SaveTextTagHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Texttag */));
JASSFN(SaveTimerDialogHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Timerdialog */));
JASSFN(SaveTimerHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Timer */));
JASSFN(SaveTrackableHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Trackable */));
JASSFN(SaveTriggerActionHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Triggeraction */));
JASSFN(SaveTriggerConditionHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Triggercondition */));
JASSFN(SaveTriggerEventHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Event */));
JASSFN(SaveTriggerHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Trigger */));
JASSFN(SaveUbersplatHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Ubersplat */));
JASSFN(SaveUnitHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Unit */));
JASSFN(SaveUnitPoolHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Unitpool */));
JASSFN(SaveWidgetHandle, bool __cdecl, (HANDLE /* Hashtable */, int, int, HANDLE /* Widget */));
JASSFN(SelectHeroSkill, void __cdecl, (HANDLE /* Unit */, int));
JASSFN(SelectUnit, void __cdecl, (HANDLE /* Unit */, bool));
JASSFN(SetAllItemTypeSlots, void __cdecl, ());
JASSFN(SetAllUnitTypeSlots, void __cdecl, ());
JASSFN(SetAllyColorFilterState, void __cdecl, ());
JASSFN(SetAltMinimapIcon, void __cdecl, (RCString*));
JASSFN(SetBlight, void __cdecl, (HANDLE /* Player */, float*, float*, float*, bool));
JASSFN(SetBlightLoc, void __cdecl, (HANDLE /* Player */, HANDLE /* Location */, float*, bool));
JASSFN(SetBlightPoint, void __cdecl, (HANDLE /* Player */, float*, float*, bool));
JASSFN(SetBlightRect, void __cdecl, (HANDLE /* Player */, HANDLE /* Rect */, bool));
JASSFN(SetCameraBounds, void __cdecl, (float*, float*, float*, float*, float*, float*, float*, float*));
JASSFN(SetCameraField, void __cdecl, (HANDLE /* Camerafield */, float*, float*));
JASSFN(SetCameraOrientController, void __cdecl, (HANDLE /* Unit */, float*, float*));
JASSFN(SetCameraPosition, void __cdecl, (float*, float*));
JASSFN(SetCameraQuickPosition, void __cdecl, (float*, float*));
JASSFN(SetCameraRotateMode, void __cdecl, (float*, float*, float*, float*));
JASSFN(SetCameraTargetController, void __cdecl, (HANDLE /* Unit */, float*, float*, bool));
JASSFN(SetCampaignAvailable, void __cdecl, (int, bool));
JASSFN(SetCampaignMenuRace, void __cdecl, (HANDLE /* Race */));
JASSFN(SetCampaignMenuRaceEx, void __cdecl, ());
JASSFN(SetCineFilterBlendMode, void __cdecl, (HANDLE /* Blendmode */));
JASSFN(SetCineFilterDuration, void __cdecl, (float*));
JASSFN(SetCineFilterEndColor, void __cdecl, (int, int, int, int));
JASSFN(SetCineFilterEndUV, void __cdecl, (float*, float*, float*, float*));
JASSFN(SetCineFilterStartColor, void __cdecl, (int, int, int, int));
JASSFN(SetCineFilterStartUV, void __cdecl, (float*, float*, float*, float*));
JASSFN(SetCineFilterTexMapFlags, void __cdecl, (HANDLE /* Texmapflags */));
JASSFN(SetCineFilterTexture, void __cdecl, (RCString*));
JASSFN(SetCinematicCamera, void __cdecl, (RCString*));
JASSFN(SetCinematicScene, void __cdecl, (int, HANDLE /* Playercolor */, RCString*, RCString*, float*, float*));
JASSFN(SetCreatureDensity, void __cdecl, (HANDLE /* Mapdensity */));
JASSFN(SetCreepCampFilterState, void __cdecl, ());
JASSFN(SetCustomCampaignButtonVisible, void __cdecl, (int, bool));
JASSFN(SetDayNightModels, void __cdecl, (RCString*, RCString*));
JASSFN(SetDefaultDifficulty, void __cdecl, (HANDLE /* Gamedifficulty */));
JASSFN(SetDestructableAnimation, void __cdecl, (HANDLE /* Destructable */, RCString*));
JASSFN(SetDestructableAnimationSpeed, void __cdecl, (HANDLE /* Destructable */, float*));
JASSFN(SetDestructableInvulnerable, void __cdecl, (HANDLE /* Destructable */, bool));
JASSFN(SetDestructableLife, void __cdecl, (HANDLE /* Destructable */, float*));
JASSFN(SetDestructableMaxLife, void __cdecl, (HANDLE /* Destructable */, float*));
JASSFN(SetDestructableOccluderHeight, void __cdecl, (HANDLE /* Destructable */, float*));
JASSFN(SetDoodadAnimation, void __cdecl, (float*, float*, float*, int, bool, RCString*, bool));
JASSFN(SetDoodadAnimationRect, void __cdecl, (HANDLE /* Rect */, int, RCString*, bool));
JASSFN(SetEdCinematicAvailable, void __cdecl, (int, bool));
JASSFN(SetFloatGameState, void __cdecl, (HANDLE /* Fgamestate */, float*));
JASSFN(SetFogStateRadius, void __cdecl, (HANDLE /* Player */, HANDLE /* Fogstate */, float*, float*, float*, bool));
JASSFN(SetFogStateRadiusLoc, void __cdecl, (HANDLE /* Player */, HANDLE /* Fogstate */, HANDLE /* Location */, float*, bool));
JASSFN(SetFogStateRect, void __cdecl, (HANDLE /* Player */, HANDLE /* Fogstate */, HANDLE /* Rect */, bool));
JASSFN(SetGameDifficulty, void __cdecl, (HANDLE /* Gamedifficulty */));
JASSFN(SetGamePlacement, void __cdecl, (HANDLE /* Placement */));
JASSFN(SetGameSpeed, void __cdecl, (HANDLE /* Gamespeed */));
JASSFN(SetGameTypeSupported, void __cdecl, (HANDLE /* Gametype */, bool));
JASSFN(SetHeroAgi, void __cdecl, (HANDLE /* Unit */, int, bool));
JASSFN(SetHeroInt, void __cdecl, (HANDLE /* Unit */, int, bool));
JASSFN(SetHeroLevel, void __cdecl, (HANDLE /* Unit */, int, bool));
JASSFN(SetHeroStr, void __cdecl, (HANDLE /* Unit */, int, bool));
JASSFN(SetHeroXP, void __cdecl, (HANDLE /* Unit */, int, bool));
JASSFN(SetImageAboveWater, void __cdecl, (HANDLE /* Image */, bool, bool));
JASSFN(SetImageColor, void __cdecl, (HANDLE /* Image */, int, int, int, int));
JASSFN(SetImageConstantHeight, void __cdecl, (HANDLE /* Image */, bool, float*));
JASSFN(SetImagePosition, void __cdecl, (HANDLE /* Image */, float*, float*, float*));
JASSFN(SetImageRender, void __cdecl, (HANDLE /* Image */, bool));
JASSFN(SetImageRenderAlways, void __cdecl, (HANDLE /* Image */, bool));
JASSFN(SetImageType, void __cdecl, (HANDLE /* Image */, int));
JASSFN(SetIntegerGameState, void __cdecl, (HANDLE /* Igamestate */, int));
JASSFN(SetIntroShotModel, void __cdecl, (RCString*));
JASSFN(SetIntroShotText, void __cdecl, (RCString*));
JASSFN(SetItemCharges, void __cdecl, (HANDLE /* Item */, int));
JASSFN(SetItemDropID, void __cdecl, (HANDLE /* Item */, int));
JASSFN(SetItemDropOnDeath, void __cdecl, (HANDLE /* Item */, bool));
JASSFN(SetItemDroppable, void __cdecl, (HANDLE /* Item */, bool));
JASSFN(SetItemInvulnerable, void __cdecl, (HANDLE /* Item */, bool));
JASSFN(SetItemPawnable, void __cdecl, (HANDLE /* Item */, bool));
JASSFN(SetItemPlayer, void __cdecl, (HANDLE /* Item */, HANDLE /* Player */, bool));
JASSFN(SetItemPosition, void __cdecl, (HANDLE /* Item */, float*, float*));
JASSFN(SetItemTypeSlots, void __cdecl, (HANDLE /* Unit */, int));
JASSFN(SetItemUserData, void __cdecl, (HANDLE /* Item */, int));
JASSFN(SetItemVisible, void __cdecl, (HANDLE /* Item */, bool));
JASSFN(SetLightningColor, bool __cdecl, (HANDLE /* Lightning */, float*, float*, float*, float*));
JASSFN(SetMapDescription, void __cdecl, (RCString*));
JASSFN(SetMapFlag, void __cdecl, (HANDLE /* Mapflag */, bool));
JASSFN(SetMapMusic, void __cdecl, (RCString*, bool, int));
JASSFN(SetMapName, void __cdecl, (RCString*));
JASSFN(SetMissionAvailable, void __cdecl, (int, int, bool));
JASSFN(SetMusicPlayPosition, void __cdecl, ());
JASSFN(SetMusicVolume, void __cdecl, ());
JASSFN(SetOpCinematicAvailable, void __cdecl, (int, bool));
JASSFN(SetPlayerAbilityAvailable, void __cdecl, (HANDLE /* Player */, int, bool));
JASSFN(SetPlayerAlliance, void __cdecl, (HANDLE /* Player */, HANDLE /* Player */, HANDLE /* Alliancetype */, bool));
JASSFN(SetPlayerColor, void __cdecl, (HANDLE /* Player */, HANDLE /* Playercolor */));
JASSFN(SetPlayerController, void __cdecl, (HANDLE /* Player */, HANDLE /* Mapcontrol */));
JASSFN(SetPlayerHandicap, void __cdecl, (HANDLE /* Player */, float*));
JASSFN(SetPlayerHandicapXP, void __cdecl, (HANDLE /* Player */, float*));
JASSFN(SetPlayerName, void __cdecl, (HANDLE /* Player */, RCString*));
JASSFN(SetPlayerOnScoreScreen, void __cdecl, (HANDLE /* Player */, bool));
JASSFN(SetPlayerRacePreference, void __cdecl, (HANDLE /* Player */, HANDLE /* Racepreference */));
JASSFN(SetPlayerRaceSelectable, void __cdecl, (HANDLE /* Player */, bool));
JASSFN(SetPlayerStartLocation, void __cdecl, (HANDLE /* Player */, int));
JASSFN(SetPlayerState, void __cdecl, (HANDLE /* Player */, HANDLE /* Playerstate */, int));
JASSFN(SetPlayerTaxRate, void __cdecl, (HANDLE /* Player */, HANDLE /* Player */, HANDLE /* Playerstate */, int));
JASSFN(SetPlayerTeam, void __cdecl, (HANDLE /* Player */, int));
JASSFN(SetPlayerTechMaxAllowed, void __cdecl, (HANDLE /* Player */, int, int));
JASSFN(SetPlayerTechResearched, void __cdecl, (HANDLE /* Player */, int, int));
JASSFN(SetPlayerUnitsOwner, void __cdecl, (HANDLE /* Player */, int));
JASSFN(SetPlayers, void __cdecl, ());
JASSFN(SetRandomSeed, void __cdecl, ());
JASSFN(SetRect, void __cdecl, (HANDLE /* Rect */, float*, float*, float*, float*));
JASSFN(SetRectFromLoc, void __cdecl, (HANDLE /* Rect */, HANDLE /* Location */, HANDLE /* Location */));
JASSFN(SetReservedLocalHeroButtons, void __cdecl, ());
JASSFN(SetResourceAmount, void __cdecl, (HANDLE /* Unit */, int));
JASSFN(SetResourceDensity, void __cdecl, (HANDLE /* Mapdensity */));
JASSFN(SetSkyModel, void __cdecl, (RCString*));
JASSFN(SetSoundChannel, void __cdecl, (HANDLE /* Sound */, int));
JASSFN(SetSoundConeAngles, void __cdecl, (HANDLE /* Sound */, float*, float*, int));
JASSFN(SetSoundConeOrientation, void __cdecl, (HANDLE /* Sound */, float*, float*, float*));
JASSFN(SetSoundDistanceCutoff, void __cdecl, (HANDLE /* Sound */, float*));
JASSFN(SetSoundDistances, void __cdecl, (HANDLE /* Sound */, float*, float*));
JASSFN(SetSoundDuration, void __cdecl, (HANDLE /* Sound */, int));
JASSFN(SetSoundParamsFromLabel, void __cdecl, (HANDLE /* Sound */, RCString*));
JASSFN(SetSoundPitch, void __cdecl, (HANDLE /* Sound */, float*));
JASSFN(SetSoundPlayPosition, void __cdecl, (HANDLE /* Sound */, int));
JASSFN(SetSoundPosition, void __cdecl, (HANDLE /* Sound */, float*, float*, float*));
JASSFN(SetSoundVelocity, void __cdecl, (HANDLE /* Sound */, float*, float*, float*));
JASSFN(SetSoundVolume, void __cdecl, (HANDLE /* Sound */, int));
JASSFN(SetStackedSound, void __cdecl, (RCString*, float*, float*));
JASSFN(SetStackedSoundRect, void __cdecl, (RCString*, HANDLE /* Rect */));
JASSFN(SetStartLocPrio, void __cdecl, (int, int, int, HANDLE /* Startlocprio */));
JASSFN(SetStartLocPrioCount, void __cdecl, (int, int));
JASSFN(SetTeams, void __cdecl, ());
JASSFN(SetTerrainFog, void __cdecl, (float*, float*, float*, float*, float*));
JASSFN(SetTerrainFogEx, void __cdecl, (int, float*, float*, float*, float*, float*, float*));
JASSFN(SetTerrainPathable, void __cdecl, (float*, float*, HANDLE /* Pathingtype */, bool));
JASSFN(SetTerrainType, void __cdecl, (float*, float*, int, int, int, int));
JASSFN(SetTextTagAge, void __cdecl, (HANDLE /* Texttag */, float*));
JASSFN(SetTextTagColor, void __cdecl, (HANDLE /* Texttag */, int, int, int, int));
JASSFN(SetTextTagFadepoint, void __cdecl, (HANDLE /* Texttag */, float*));
JASSFN(SetTextTagLifespan, void __cdecl, (HANDLE /* Texttag */, float*));
JASSFN(SetTextTagPermanent, void __cdecl, (HANDLE /* Texttag */, bool));
JASSFN(SetTextTagPos, void __cdecl, (HANDLE /* Texttag */, float*, float*, float*));
JASSFN(SetTextTagPosUnit, void __cdecl, (HANDLE /* Texttag */, HANDLE /* Unit */, float*));
JASSFN(SetTextTagSuspended, void __cdecl, (HANDLE /* Texttag */, bool));
JASSFN(SetTextTagText, void __cdecl, (HANDLE /* Texttag */, RCString*, float*));
JASSFN(SetTextTagVelocity, void __cdecl, (HANDLE /* Texttag */, float*, float*));
JASSFN(SetTextTagVisibility, void __cdecl, (HANDLE /* Texttag */, bool));
JASSFN(SetThematicMusicPlayPosition, void __cdecl, ());
JASSFN(SetTimeOfDayScale, void __cdecl, (float*));
JASSFN(SetTutorialCleared, void __cdecl, ());
JASSFN(SetUbersplatRender, void __cdecl, (HANDLE /* Ubersplat */, bool));
JASSFN(SetUbersplatRenderAlways, void __cdecl, (HANDLE /* Ubersplat */, bool));
JASSFN(SetUnitAbilityLevel, int __cdecl, (HANDLE /* Unit */, int, int));
JASSFN(SetUnitAcquireRange, void __cdecl, (HANDLE /* Unit */, float*));
JASSFN(SetUnitAnimation, void __cdecl, (HANDLE /* Unit */, RCString*));
JASSFN(SetUnitAnimationByIndex, void __cdecl, (HANDLE /* Unit */, int));
JASSFN(SetUnitAnimationWithRarity, void __cdecl, (HANDLE /* Unit */, RCString*, HANDLE /* Raritycontrol */));
JASSFN(SetUnitBlendTime, void __cdecl, (HANDLE /* Unit */, float*));
JASSFN(SetUnitColor, void __cdecl, (HANDLE /* Unit */, HANDLE /* Playercolor */));
JASSFN(SetUnitCreepGuard, void __cdecl, (HANDLE /* Unit */, bool));
JASSFN(SetUnitExploded, void __cdecl, (HANDLE /* Unit */, bool));
JASSFN(SetUnitFacing, void __cdecl, (HANDLE /* Unit */, float*));
JASSFN(SetUnitFacingTimed, void __cdecl, (HANDLE /* Unit */, float*, float*));
JASSFN(SetUnitFlyHeight, void __cdecl, (HANDLE /* Unit */, float*, float*));
JASSFN(SetUnitFog, void __cdecl, (float*, float*, float*, float*, float*));
JASSFN(SetUnitInvulnerable, void __cdecl, (HANDLE /* Unit */, bool));
JASSFN(SetUnitLookAt, void __cdecl, (HANDLE /* Unit */, RCString*, HANDLE /* Unit */, float*, float*, float*));
JASSFN(SetUnitMoveSpeed, void __cdecl, (HANDLE /* Unit */, float*));
JASSFN(SetUnitOwner, void __cdecl, (HANDLE /* Unit */, HANDLE /* Player */, bool));
JASSFN(SetUnitPathing, void __cdecl, (HANDLE /* Unit */, bool));
JASSFN(SetUnitPosition, void __cdecl, (HANDLE /* Unit */, float*, float*));
JASSFN(SetUnitPositionLoc, void __cdecl, (HANDLE /* Unit */, HANDLE /* Location */));
JASSFN(SetUnitPropWindow, void __cdecl, (HANDLE /* Unit */, float*));
JASSFN(SetUnitRescuable, void __cdecl, (HANDLE /* Unit */, HANDLE /* Player */, bool));
JASSFN(SetUnitRescueRange, void __cdecl, (HANDLE /* Unit */, float*));
JASSFN(SetUnitScale, void __cdecl, (HANDLE /* Unit */, float*, float*, float*));
JASSFN(SetUnitState, void __cdecl, (HANDLE /* Unit */, HANDLE /* Unitstate */, float*));
JASSFN(SetUnitTimeScale, void __cdecl, (HANDLE /* Unit */, float*));
JASSFN(SetUnitTurnSpeed, void __cdecl, (HANDLE /* Unit */, float*));
JASSFN(SetUnitTypeSlots, void __cdecl, (HANDLE /* Unit */, int));
JASSFN(SetUnitUseFood, void __cdecl, (HANDLE /* Unit */, bool));
JASSFN(SetUnitUserData, void __cdecl, (HANDLE /* Unit */, int));
JASSFN(SetUnitVertexColor, void __cdecl, (HANDLE /* Unit */, int, int, int, int));
JASSFN(SetUnitX, void __cdecl, (HANDLE /* Unit */, float*));
JASSFN(SetUnitY, void __cdecl, (HANDLE /* Unit */, float*));
JASSFN(SetWaterBaseColor, void __cdecl, (int, int, int, int));
JASSFN(SetWaterDeforms, void __cdecl, ());
JASSFN(SetWidgetLife, void __cdecl, (HANDLE /* Widget */, float*));
JASSFN(ShowDestructable, void __cdecl, (HANDLE /* Destructable */, bool));
JASSFN(ShowImage, void __cdecl, (HANDLE /* Image */, bool));
JASSFN(ShowInterface, void __cdecl, (bool, float*));
JASSFN(ShowUbersplat, void __cdecl, (HANDLE /* Ubersplat */, bool));
JASSFN(ShowUnit, void __cdecl, (HANDLE /* Unit */, bool));
JASSFN(Sin, DWFP __cdecl, (float*));
JASSFN(SquareRoot, DWFP __cdecl, (float*));
JASSFN(StartCampaignAI, void __cdecl, (HANDLE /* Player */, RCString*));
JASSFN(StartMeleeAI, void __cdecl, (HANDLE /* Player */, RCString*));
JASSFN(StartSound, void __cdecl, (HANDLE /* Sound */));
JASSFN(StopCamera, void __cdecl, ());
JASSFN(StopMusic, void __cdecl, ());
JASSFN(StopSound, void __cdecl, (HANDLE /* Sound */, bool, bool));
JASSFN(StoreBoolean, void __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*, bool));
JASSFN(StoreInteger, void __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*, int));
JASSFN(StoreReal, void __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*, float*));
JASSFN(StoreString, bool __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*, RCString*));
JASSFN(StoreUnit, bool __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*, HANDLE /* Unit */));
JASSFN(StringCase, HANDLE /*String*/ __cdecl, (RCString*, bool));
JASSFN(StringHash, int __cdecl, (RCString*));
JASSFN(StringLength, int __cdecl, (RCString*));
JASSFN(SubString, HANDLE /*String*/ __cdecl, (RCString*, int, int));
JASSFN(SuspendHeroXP, void __cdecl, (HANDLE /* Unit */, bool));
JASSFN(SuspendTimeOfDay, void __cdecl, ());
JASSFN(SyncSelections, void __cdecl, ());
JASSFN(SyncStoredBoolean, void __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*));
JASSFN(SyncStoredInteger, void __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*));
JASSFN(SyncStoredReal, void __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*));
JASSFN(SyncStoredString, void __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*));
JASSFN(SyncStoredUnit, void __cdecl, (HANDLE /* Gamecache */, RCString*, RCString*));
JASSFN(Tan, DWFP __cdecl, (float*));
JASSFN(TerrainDeformCrater, HANDLE /* Terraindeformation */ __cdecl, (float*, float*, float*, float*, int, bool));
JASSFN(TerrainDeformRandom, HANDLE /* Terraindeformation */ __cdecl, (float*, float*, float*, float*, float*, int, int));
JASSFN(TerrainDeformRipple, HANDLE /* Terraindeformation */ __cdecl, (float*, float*, float*, float*, int, int, float*, float*, float*, bool));
JASSFN(TerrainDeformStop, void __cdecl, (HANDLE /* Terraindeformation */, int));
JASSFN(TerrainDeformStopAll, void __cdecl, ());
JASSFN(TerrainDeformWave, HANDLE /* Terraindeformation */ __cdecl, (float*, float*, float*, float*, float*, float*, float*, float*, int, int));
JASSFN(TimerDialogDisplay, void __cdecl, (HANDLE /* Timerdialog */, bool));
JASSFN(TimerDialogSetRealTimeRemaining, void __cdecl, (HANDLE /* Timerdialog */, float*));
JASSFN(TimerDialogSetSpeed, void __cdecl, (HANDLE /* Timerdialog */, float*));
JASSFN(TimerDialogSetTimeColor, void __cdecl, (HANDLE /* Timerdialog */, int, int, int, int));
JASSFN(TimerDialogSetTitle, void __cdecl, (HANDLE /* Timerdialog */, RCString*));
JASSFN(TimerDialogSetTitleColor, void __cdecl, (HANDLE /* Timerdialog */, int, int, int, int));
JASSFN(TimerGetElapsed, DWFP __cdecl, (HANDLE /* Timer */));
JASSFN(TimerGetRemaining, DWFP __cdecl, (HANDLE /* Timer */));
JASSFN(TimerGetTimeout, DWFP __cdecl, (HANDLE /* Timer */));
JASSFN(TimerStart, void __cdecl, (HANDLE /* Timer */, float*, bool, DWORD));
JASSFN(TriggerAddAction, HANDLE /* Triggeraction */ __cdecl, (HANDLE /* Trigger */, DWORD));
JASSFN(TriggerAddCondition, HANDLE /* Triggercondition */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Boolexpr */));
JASSFN(TriggerClearActions, void __cdecl, (HANDLE /* Trigger */));
JASSFN(TriggerClearConditions, void __cdecl, (HANDLE /* Trigger */));
JASSFN(TriggerEvaluate, bool __cdecl, (HANDLE /* Trigger */));
JASSFN(TriggerExecute, void __cdecl, (HANDLE /* Trigger */));
JASSFN(TriggerExecuteWait, void __cdecl, (HANDLE /* Trigger */));
JASSFN(TriggerRegisterDeathEvent, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Widget */));
JASSFN(TriggerRegisterDialogButtonEvent, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Button */));
JASSFN(TriggerRegisterDialogEvent, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Dialog */));
JASSFN(TriggerRegisterEnterRegion, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Region */, HANDLE /* Boolexpr */));
JASSFN(TriggerRegisterFilterUnitEvent, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Unit */, HANDLE /* Unitevent */, HANDLE /* Boolexpr */));
JASSFN(TriggerRegisterGameEvent, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Gameevent */));
JASSFN(TriggerRegisterGameStateEvent, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Gamestate */, HANDLE /* Limitop */, float*));
JASSFN(TriggerRegisterLeaveRegion, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Region */, HANDLE /* Boolexpr */));
JASSFN(TriggerRegisterPlayerAllianceChange, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Player */, HANDLE /* Alliancetype */));
JASSFN(TriggerRegisterPlayerChatEvent, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Player */, RCString*, bool));
JASSFN(TriggerRegisterPlayerEvent, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Player */, HANDLE /* Playerevent */));
JASSFN(TriggerRegisterPlayerStateEvent, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Player */, HANDLE /* Playerstate */, HANDLE /* Limitop */, float*));
JASSFN(TriggerRegisterPlayerUnitEvent, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Player */, HANDLE /* Playerunitevent */, HANDLE /* Boolexpr */));
JASSFN(TriggerRegisterTimerEvent, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, float*, bool));
JASSFN(TriggerRegisterTimerExpireEvent, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Timer */));
JASSFN(TriggerRegisterTrackableHitEvent, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Trackable */));
JASSFN(TriggerRegisterTrackableTrackEvent, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Trackable */));
JASSFN(TriggerRegisterUnitEvent, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Unit */, HANDLE /* Unitevent */));
JASSFN(TriggerRegisterUnitInRange, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Unit */, float*, HANDLE /* Boolexpr */));
JASSFN(TriggerRegisterUnitStateEvent, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, HANDLE /* Unit */, HANDLE /* Unitstate */, HANDLE /* Limitop */, float*));
JASSFN(TriggerRegisterVariableEvent, HANDLE /* Event */ __cdecl, (HANDLE /* Trigger */, RCString*, HANDLE /* Limitop */, float*));
JASSFN(TriggerRemoveAction, void __cdecl, (HANDLE /* Trigger */, HANDLE /* Triggeraction */));
JASSFN(TriggerRemoveCondition, void __cdecl, (HANDLE /* Trigger */, HANDLE /* Triggercondition */));
JASSFN(TriggerSleepAction, void __cdecl, (float*));
JASSFN(TriggerSyncReady, void __cdecl, ());
JASSFN(TriggerSyncStart, void __cdecl, ());
JASSFN(TriggerWaitForSound, void __cdecl, (HANDLE /* Sound */, float*));
JASSFN(TriggerWaitOnSleeps, void __cdecl, (HANDLE /* Trigger */, bool));
JASSFN(UnitAddAbility, bool __cdecl, (HANDLE /* Unit */, int));
JASSFN(UnitAddIndicator, void __cdecl, (HANDLE /* Unit */, int, int, int, int));
JASSFN(UnitAddItem, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Item */));
JASSFN(UnitAddItemById, HANDLE /* Item */ __cdecl, (HANDLE /* Unit */, int));
JASSFN(UnitAddItemToSlotById, bool __cdecl, (HANDLE /* Unit */, int, int));
JASSFN(UnitAddSleep, void __cdecl, (HANDLE /* Unit */, bool));
JASSFN(UnitAddSleepPerm, void __cdecl, (HANDLE /* Unit */, bool));
JASSFN(UnitAddType, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Unittype */));
JASSFN(UnitApplyTimedLife, void __cdecl, (HANDLE /* Unit */, int, float*));
JASSFN(UnitCanSleep, bool __cdecl, (HANDLE /* Unit */));
JASSFN(UnitCanSleepPerm, bool __cdecl, (HANDLE /* Unit */));
JASSFN(UnitCountBuffsEx, int __cdecl, (HANDLE /* Unit */, bool, bool, bool, bool, bool, bool, bool));
JASSFN(UnitDamagePoint, bool __cdecl, (HANDLE /* Unit */, float*, float*, float*, float*, float*, bool, bool, HANDLE /* Attacktype */, HANDLE /* Damagetype */, HANDLE /* Weapontype */));
JASSFN(UnitDamageTarget, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Widget */, float*, bool, bool, HANDLE /* Attacktype */, HANDLE /* Damagetype */, HANDLE /* Weapontype */));
JASSFN(UnitDropItemPoint, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Item */, float*, float*));
JASSFN(UnitDropItemSlot, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Item */, int));
JASSFN(UnitDropItemTarget, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Item */, HANDLE /* Widget */));
JASSFN(UnitHasBuffsEx, bool __cdecl, (HANDLE /* Unit */, bool, bool, bool, bool, bool, bool, bool));
JASSFN(UnitHasItem, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Item */));
JASSFN(UnitId, int __cdecl, (RCString*));
JASSFN(UnitId2String, HANDLE /*String*/ __cdecl, ());
JASSFN(UnitIgnoreAlarm, bool __cdecl, (HANDLE /* Unit */, bool));
JASSFN(UnitIgnoreAlarmToggled, bool __cdecl, (HANDLE /* Unit */));
JASSFN(UnitInventorySize, int __cdecl, (HANDLE /* Unit */));
JASSFN(UnitIsSleeping, bool __cdecl, (HANDLE /* Unit */));
JASSFN(UnitItemInSlot, HANDLE /* Item */ __cdecl, (HANDLE /* Unit */, int));
JASSFN(UnitMakeAbilityPermanent, bool __cdecl, (HANDLE /* Unit */, bool, int));
JASSFN(UnitModifySkillPoints, bool __cdecl, (HANDLE /* Unit */, int));
JASSFN(UnitPauseTimedLife, void __cdecl, (HANDLE /* Unit */, bool));
JASSFN(UnitPoolAddUnitType, void __cdecl, (HANDLE /* Unitpool */, int, float*));
JASSFN(UnitPoolRemoveUnitType, void __cdecl, (HANDLE /* Unitpool */, int));
JASSFN(UnitRemoveAbility, bool __cdecl, (HANDLE /* Unit */, int));
JASSFN(UnitRemoveBuffs, void __cdecl, (HANDLE /* Unit */, bool, bool));
JASSFN(UnitRemoveBuffsEx, void __cdecl, (HANDLE /* Unit */, bool, bool, bool, bool, bool, bool, bool));
JASSFN(UnitRemoveItem, void __cdecl, (HANDLE /* Unit */, HANDLE /* Item */));
JASSFN(UnitRemoveItemFromSlot, HANDLE /* Item */ __cdecl, (HANDLE /* Unit */, int));
JASSFN(UnitRemoveType, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Unittype */));
JASSFN(UnitResetCooldown, void __cdecl, (HANDLE /* Unit */));
JASSFN(UnitSetConstructionProgress, void __cdecl, (HANDLE /* Unit */, int));
JASSFN(UnitSetUpgradeProgress, void __cdecl, (HANDLE /* Unit */, int));
JASSFN(UnitSetUsesAltIcon, void __cdecl, (HANDLE /* Unit */, bool));
JASSFN(UnitShareVision, void __cdecl, (HANDLE /* Unit */, HANDLE /* Player */, bool));
JASSFN(UnitStripHeroLevel, bool __cdecl, (HANDLE /* Unit */, int));
JASSFN(UnitSuspendDecay, void __cdecl, (HANDLE /* Unit */, bool));
JASSFN(UnitUseItem, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Item */));
JASSFN(UnitUseItemPoint, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Item */, float*, float*));
JASSFN(UnitUseItemTarget, bool __cdecl, (HANDLE /* Unit */, HANDLE /* Item */, HANDLE /* Widget */));
JASSFN(UnitWakeUp, void __cdecl, (HANDLE /* Unit */));
JASSFN(UnregisterStackedSound, void __cdecl, (HANDLE /* Sound */, bool, float*, float*));
JASSFN(VersionCompatible, bool __cdecl, (HANDLE /* Version */));
JASSFN(VersionGet, HANDLE /* Version */ __cdecl, ());
JASSFN(VersionSupported, bool __cdecl, (HANDLE /* Version */));
JASSFN(VolumeGroupReset, void __cdecl, ());
JASSFN(VolumeGroupSetVolume, void __cdecl, (HANDLE /* Volumegroup */, float*));
JASSFN(WaygateActivate, void __cdecl, (HANDLE /* Unit */, bool));
JASSFN(WaygateGetDestinationX, DWFP __cdecl, (HANDLE /* Unit */));
JASSFN(WaygateGetDestinationY, DWFP __cdecl, (HANDLE /* Unit */));
JASSFN(WaygateIsActive, bool __cdecl, (HANDLE /* Unit */));
JASSFN(WaygateSetDestination, void __cdecl, (HANDLE /* Unit */, float*, float*));

#endif // JASS_h__